/*
 * Corresponsales.Command.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Corresponsales.Command.Client;
using Corresponsales.Command.Model;

namespace Corresponsales.Command.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsuarioApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Corresponsales.Command.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actualizaEstadoUsuarioRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Object</returns>
        Object ActualizaEstadoUsuario(ActualizaEstadoUsuarioRequest? actualizaEstadoUsuarioRequest = default(ActualizaEstadoUsuarioRequest?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Command.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actualizaEstadoUsuarioRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> ActualizaEstadoUsuarioWithHttpInfo(ActualizaEstadoUsuarioRequest? actualizaEstadoUsuarioRequest = default(ActualizaEstadoUsuarioRequest?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Corresponsales.Command.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="creaUsuarioRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Object</returns>
        Object CreaUsuario(CreaUsuarioRequest? creaUsuarioRequest = default(CreaUsuarioRequest?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Command.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="creaUsuarioRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> CreaUsuarioWithHttpInfo(CreaUsuarioRequest? creaUsuarioRequest = default(CreaUsuarioRequest?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsuarioApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Command.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actualizaEstadoUsuarioRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> ActualizaEstadoUsuarioAsync(ActualizaEstadoUsuarioRequest? actualizaEstadoUsuarioRequest = default(ActualizaEstadoUsuarioRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Command.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actualizaEstadoUsuarioRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ActualizaEstadoUsuarioWithHttpInfoAsync(ActualizaEstadoUsuarioRequest? actualizaEstadoUsuarioRequest = default(ActualizaEstadoUsuarioRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Command.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="creaUsuarioRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> CreaUsuarioAsync(CreaUsuarioRequest? creaUsuarioRequest = default(CreaUsuarioRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Command.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="creaUsuarioRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> CreaUsuarioWithHttpInfoAsync(CreaUsuarioRequest? creaUsuarioRequest = default(CreaUsuarioRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsuarioApi : IUsuarioApiSync, IUsuarioApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UsuarioApi : IUsuarioApi
    {
        private Corresponsales.Command.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UsuarioApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UsuarioApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsuarioApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UsuarioApi(string basePath)
        {
            this.Configuration = Corresponsales.Command.Client.Configuration.MergeConfigurations(
                Corresponsales.Command.Client.GlobalConfiguration.Instance,
                new Corresponsales.Command.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Corresponsales.Command.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Corresponsales.Command.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Corresponsales.Command.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsuarioApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UsuarioApi(Corresponsales.Command.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Corresponsales.Command.Client.Configuration.MergeConfigurations(
                Corresponsales.Command.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Corresponsales.Command.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Corresponsales.Command.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Corresponsales.Command.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsuarioApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public UsuarioApi(Corresponsales.Command.Client.ISynchronousClient client, Corresponsales.Command.Client.IAsynchronousClient asyncClient, Corresponsales.Command.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Corresponsales.Command.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Corresponsales.Command.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Corresponsales.Command.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Corresponsales.Command.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Corresponsales.Command.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Command.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actualizaEstadoUsuarioRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Object</returns>
        public Object ActualizaEstadoUsuario(ActualizaEstadoUsuarioRequest? actualizaEstadoUsuarioRequest = default(ActualizaEstadoUsuarioRequest?), int operationIndex = 0)
        {
            Corresponsales.Command.Client.ApiResponse<Object> localVarResponse = ActualizaEstadoUsuarioWithHttpInfo(actualizaEstadoUsuarioRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Command.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actualizaEstadoUsuarioRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object</returns>
        public Corresponsales.Command.Client.ApiResponse<Object> ActualizaEstadoUsuarioWithHttpInfo(ActualizaEstadoUsuarioRequest? actualizaEstadoUsuarioRequest = default(ActualizaEstadoUsuarioRequest?), int operationIndex = 0)
        {
            Corresponsales.Command.Client.RequestOptions localVarRequestOptions = new Corresponsales.Command.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Corresponsales.Command.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Corresponsales.Command.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = actualizaEstadoUsuarioRequest;

            localVarRequestOptions.Operation = "UsuarioApi.ActualizaEstadoUsuario";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/Usuario/ActualizaEstadoUsuario", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ActualizaEstadoUsuario", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Command.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actualizaEstadoUsuarioRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> ActualizaEstadoUsuarioAsync(ActualizaEstadoUsuarioRequest? actualizaEstadoUsuarioRequest = default(ActualizaEstadoUsuarioRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Corresponsales.Command.Client.ApiResponse<Object> localVarResponse = await ActualizaEstadoUsuarioWithHttpInfoAsync(actualizaEstadoUsuarioRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Command.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actualizaEstadoUsuarioRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<Corresponsales.Command.Client.ApiResponse<Object>> ActualizaEstadoUsuarioWithHttpInfoAsync(ActualizaEstadoUsuarioRequest? actualizaEstadoUsuarioRequest = default(ActualizaEstadoUsuarioRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Corresponsales.Command.Client.RequestOptions localVarRequestOptions = new Corresponsales.Command.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Corresponsales.Command.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Corresponsales.Command.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = actualizaEstadoUsuarioRequest;

            localVarRequestOptions.Operation = "UsuarioApi.ActualizaEstadoUsuario";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/Usuario/ActualizaEstadoUsuario", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ActualizaEstadoUsuario", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Command.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="creaUsuarioRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Object</returns>
        public Object CreaUsuario(CreaUsuarioRequest? creaUsuarioRequest = default(CreaUsuarioRequest?), int operationIndex = 0)
        {
            Corresponsales.Command.Client.ApiResponse<Object> localVarResponse = CreaUsuarioWithHttpInfo(creaUsuarioRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Command.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="creaUsuarioRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object</returns>
        public Corresponsales.Command.Client.ApiResponse<Object> CreaUsuarioWithHttpInfo(CreaUsuarioRequest? creaUsuarioRequest = default(CreaUsuarioRequest?), int operationIndex = 0)
        {
            Corresponsales.Command.Client.RequestOptions localVarRequestOptions = new Corresponsales.Command.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Corresponsales.Command.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Corresponsales.Command.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = creaUsuarioRequest;

            localVarRequestOptions.Operation = "UsuarioApi.CreaUsuario";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/Usuario/CreaUsuario", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreaUsuario", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Command.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="creaUsuarioRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> CreaUsuarioAsync(CreaUsuarioRequest? creaUsuarioRequest = default(CreaUsuarioRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Corresponsales.Command.Client.ApiResponse<Object> localVarResponse = await CreaUsuarioWithHttpInfoAsync(creaUsuarioRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Command.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="creaUsuarioRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<Corresponsales.Command.Client.ApiResponse<Object>> CreaUsuarioWithHttpInfoAsync(CreaUsuarioRequest? creaUsuarioRequest = default(CreaUsuarioRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Corresponsales.Command.Client.RequestOptions localVarRequestOptions = new Corresponsales.Command.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Corresponsales.Command.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Corresponsales.Command.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = creaUsuarioRequest;

            localVarRequestOptions.Operation = "UsuarioApi.CreaUsuario";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/Usuario/CreaUsuario", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreaUsuario", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
