// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosTulcan.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClActualizaEstadoUsuarioME
    {
        /// <summary>
        /// Initializes a new instance of the ClActualizaEstadoUsuarioME class.
        /// </summary>
        public ClActualizaEstadoUsuarioME()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClActualizaEstadoUsuarioME class.
        /// </summary>
        public ClActualizaEstadoUsuarioME(string codigoUsuarioCorresponsal = default(string), bool? estado = default(bool?))
        {
            CodigoUsuarioCorresponsal = codigoUsuarioCorresponsal;
            Estado = estado;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CodigoUsuarioCorresponsal")]
        public string CodigoUsuarioCorresponsal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Estado")]
        public bool? Estado { get; set; }

    }
}
