// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosTulcan.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClJsonComision
    {
        /// <summary>
        /// Initializes a new instance of the ClJsonComision class.
        /// </summary>
        public ClJsonComision()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClJsonComision class.
        /// </summary>
        public ClJsonComision(string nombreComision = default(string), double? valorComision = default(double?))
        {
            NombreComision = nombreComision;
            ValorComision = valorComision;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NombreComision")]
        public string NombreComision { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ValorComision")]
        public double? ValorComision { get; set; }

    }
}
