// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosTulcan.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClPorCodigoUsuarioCorresponsalME
    {
        /// <summary>
        /// Initializes a new instance of the ClPorCodigoUsuarioCorresponsalME
        /// class.
        /// </summary>
        public ClPorCodigoUsuarioCorresponsalME()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClPorCodigoUsuarioCorresponsalME
        /// class.
        /// </summary>
        public ClPorCodigoUsuarioCorresponsalME(string codigoUsuarioCorresponsal = default(string))
        {
            CodigoUsuarioCorresponsal = codigoUsuarioCorresponsal;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CodigoUsuarioCorresponsal")]
        public string CodigoUsuarioCorresponsal { get; set; }

    }
}
