// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosTulcan.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClPorIdentificacionClienteActivaME
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ClPorIdentificacionClienteActivaME class.
        /// </summary>
        public ClPorIdentificacionClienteActivaME()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// ClPorIdentificacionClienteActivaME class.
        /// </summary>
        public ClPorIdentificacionClienteActivaME(string identificacion = default(string), bool? estaActiva = default(bool?))
        {
            Identificacion = identificacion;
            EstaActiva = estaActiva;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Identificacion")]
        public string Identificacion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EstaActiva")]
        public bool? EstaActiva { get; set; }

    }
}
