// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFacilito.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ConsultaME
    {
        /// <summary>
        /// Initializes a new instance of the ConsultaME class.
        /// </summary>
        public ConsultaME()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConsultaME class.
        /// </summary>
        public ConsultaME(int? codigoTransaccion = default(int?), int? operador = default(int?), string producto = default(string), string codigoAuxiliar = default(string), string referencia = default(string), int? servicioBancario = default(int?), string xmlAdd = default(string))
        {
            CodigoTransaccion = codigoTransaccion;
            Operador = operador;
            Producto = producto;
            CodigoAuxiliar = codigoAuxiliar;
            Referencia = referencia;
            ServicioBancario = servicioBancario;
            XmlAdd = xmlAdd;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "codigoTransaccion")]
        public int? CodigoTransaccion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operador")]
        public int? Operador { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "producto")]
        public string Producto { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "codigoAuxiliar")]
        public string CodigoAuxiliar { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "referencia")]
        public string Referencia { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "servicioBancario")]
        public int? ServicioBancario { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "xmlAdd")]
        public string XmlAdd { get; set; }

    }
}
