// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFacilito.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ServicioFacilito
    {
        /// <summary>
        /// Initializes a new instance of the ServicioFacilito class.
        /// </summary>
        public ServicioFacilito()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ServicioFacilito class.
        /// </summary>
        public ServicioFacilito(System.Guid? id = default(System.Guid?), long? codigo = default(long?), string nombre = default(string))
        {
            Id = id;
            Codigo = codigo;
            Nombre = nombre;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "codigo")]
        public long? Codigo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nombre")]
        public string Nombre { get; set; }

    }
}
