/*
 * Corresponsales.Query.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Corresponsales.Query.Client;
using Corresponsales.Query.Model;

namespace Corresponsales.Query.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICaptacionesVistaApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveConsolidadoCuentasRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DevuelveConsolidadoCuentasResponse</returns>
        DevuelveConsolidadoCuentasResponse DevuelveConsolidadoCuentas(DevuelveConsolidadoCuentasRequest? devuelveConsolidadoCuentasRequest = default(DevuelveConsolidadoCuentasRequest?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveConsolidadoCuentasRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DevuelveConsolidadoCuentasResponse</returns>
        ApiResponse<DevuelveConsolidadoCuentasResponse> DevuelveConsolidadoCuentasWithHttpInfo(DevuelveConsolidadoCuentasRequest? devuelveConsolidadoCuentasRequest = default(DevuelveConsolidadoCuentasRequest?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveConsolidadoCuentasIdentificacionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DevuelveConsolidadoCuentasIdentificacionResponse</returns>
        DevuelveConsolidadoCuentasIdentificacionResponse DevuelveConsolidadoCuentasIdentificacion(DevuelveConsolidadoCuentasIdentificacionRequest? devuelveConsolidadoCuentasIdentificacionRequest = default(DevuelveConsolidadoCuentasIdentificacionRequest?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveConsolidadoCuentasIdentificacionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DevuelveConsolidadoCuentasIdentificacionResponse</returns>
        ApiResponse<DevuelveConsolidadoCuentasIdentificacionResponse> DevuelveConsolidadoCuentasIdentificacionWithHttpInfo(DevuelveConsolidadoCuentasIdentificacionRequest? devuelveConsolidadoCuentasIdentificacionRequest = default(DevuelveConsolidadoCuentasIdentificacionRequest?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveCuentaRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DevuelveCuentaResponse</returns>
        DevuelveCuentaResponse DevuelveCuenta(DevuelveCuentaRequest? devuelveCuentaRequest = default(DevuelveCuentaRequest?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveCuentaRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DevuelveCuentaResponse</returns>
        ApiResponse<DevuelveCuentaResponse> DevuelveCuentaWithHttpInfo(DevuelveCuentaRequest? devuelveCuentaRequest = default(DevuelveCuentaRequest?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveTiposDeCuentasDeUnClienteRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DevuelveTiposDeCuentasDeUnClienteResponse</returns>
        DevuelveTiposDeCuentasDeUnClienteResponse DevuelveTiposDeCuentasDeUnCliente(DevuelveTiposDeCuentasDeUnClienteRequest? devuelveTiposDeCuentasDeUnClienteRequest = default(DevuelveTiposDeCuentasDeUnClienteRequest?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveTiposDeCuentasDeUnClienteRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DevuelveTiposDeCuentasDeUnClienteResponse</returns>
        ApiResponse<DevuelveTiposDeCuentasDeUnClienteResponse> DevuelveTiposDeCuentasDeUnClienteWithHttpInfo(DevuelveTiposDeCuentasDeUnClienteRequest? devuelveTiposDeCuentasDeUnClienteRequest = default(DevuelveTiposDeCuentasDeUnClienteRequest?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICaptacionesVistaApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveConsolidadoCuentasRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DevuelveConsolidadoCuentasResponse</returns>
        System.Threading.Tasks.Task<DevuelveConsolidadoCuentasResponse> DevuelveConsolidadoCuentasAsync(DevuelveConsolidadoCuentasRequest? devuelveConsolidadoCuentasRequest = default(DevuelveConsolidadoCuentasRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveConsolidadoCuentasRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DevuelveConsolidadoCuentasResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DevuelveConsolidadoCuentasResponse>> DevuelveConsolidadoCuentasWithHttpInfoAsync(DevuelveConsolidadoCuentasRequest? devuelveConsolidadoCuentasRequest = default(DevuelveConsolidadoCuentasRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveConsolidadoCuentasIdentificacionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DevuelveConsolidadoCuentasIdentificacionResponse</returns>
        System.Threading.Tasks.Task<DevuelveConsolidadoCuentasIdentificacionResponse> DevuelveConsolidadoCuentasIdentificacionAsync(DevuelveConsolidadoCuentasIdentificacionRequest? devuelveConsolidadoCuentasIdentificacionRequest = default(DevuelveConsolidadoCuentasIdentificacionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveConsolidadoCuentasIdentificacionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DevuelveConsolidadoCuentasIdentificacionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DevuelveConsolidadoCuentasIdentificacionResponse>> DevuelveConsolidadoCuentasIdentificacionWithHttpInfoAsync(DevuelveConsolidadoCuentasIdentificacionRequest? devuelveConsolidadoCuentasIdentificacionRequest = default(DevuelveConsolidadoCuentasIdentificacionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveCuentaRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DevuelveCuentaResponse</returns>
        System.Threading.Tasks.Task<DevuelveCuentaResponse> DevuelveCuentaAsync(DevuelveCuentaRequest? devuelveCuentaRequest = default(DevuelveCuentaRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveCuentaRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DevuelveCuentaResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DevuelveCuentaResponse>> DevuelveCuentaWithHttpInfoAsync(DevuelveCuentaRequest? devuelveCuentaRequest = default(DevuelveCuentaRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveTiposDeCuentasDeUnClienteRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DevuelveTiposDeCuentasDeUnClienteResponse</returns>
        System.Threading.Tasks.Task<DevuelveTiposDeCuentasDeUnClienteResponse> DevuelveTiposDeCuentasDeUnClienteAsync(DevuelveTiposDeCuentasDeUnClienteRequest? devuelveTiposDeCuentasDeUnClienteRequest = default(DevuelveTiposDeCuentasDeUnClienteRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveTiposDeCuentasDeUnClienteRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DevuelveTiposDeCuentasDeUnClienteResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DevuelveTiposDeCuentasDeUnClienteResponse>> DevuelveTiposDeCuentasDeUnClienteWithHttpInfoAsync(DevuelveTiposDeCuentasDeUnClienteRequest? devuelveTiposDeCuentasDeUnClienteRequest = default(DevuelveTiposDeCuentasDeUnClienteRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICaptacionesVistaApi : ICaptacionesVistaApiSync, ICaptacionesVistaApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CaptacionesVistaApi : ICaptacionesVistaApi
    {
        private Corresponsales.Query.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CaptacionesVistaApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CaptacionesVistaApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CaptacionesVistaApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CaptacionesVistaApi(string basePath)
        {
            this.Configuration = Corresponsales.Query.Client.Configuration.MergeConfigurations(
                Corresponsales.Query.Client.GlobalConfiguration.Instance,
                new Corresponsales.Query.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Corresponsales.Query.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Corresponsales.Query.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Corresponsales.Query.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CaptacionesVistaApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CaptacionesVistaApi(Corresponsales.Query.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Corresponsales.Query.Client.Configuration.MergeConfigurations(
                Corresponsales.Query.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Corresponsales.Query.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Corresponsales.Query.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Corresponsales.Query.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CaptacionesVistaApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public CaptacionesVistaApi(Corresponsales.Query.Client.ISynchronousClient client, Corresponsales.Query.Client.IAsynchronousClient asyncClient, Corresponsales.Query.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Corresponsales.Query.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Corresponsales.Query.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Corresponsales.Query.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Corresponsales.Query.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Corresponsales.Query.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveConsolidadoCuentasRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DevuelveConsolidadoCuentasResponse</returns>
        public DevuelveConsolidadoCuentasResponse DevuelveConsolidadoCuentas(DevuelveConsolidadoCuentasRequest? devuelveConsolidadoCuentasRequest = default(DevuelveConsolidadoCuentasRequest?), int operationIndex = 0)
        {
            Corresponsales.Query.Client.ApiResponse<DevuelveConsolidadoCuentasResponse> localVarResponse = DevuelveConsolidadoCuentasWithHttpInfo(devuelveConsolidadoCuentasRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveConsolidadoCuentasRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DevuelveConsolidadoCuentasResponse</returns>
        public Corresponsales.Query.Client.ApiResponse<DevuelveConsolidadoCuentasResponse> DevuelveConsolidadoCuentasWithHttpInfo(DevuelveConsolidadoCuentasRequest? devuelveConsolidadoCuentasRequest = default(DevuelveConsolidadoCuentasRequest?), int operationIndex = 0)
        {
            Corresponsales.Query.Client.RequestOptions localVarRequestOptions = new Corresponsales.Query.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Corresponsales.Query.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Corresponsales.Query.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = devuelveConsolidadoCuentasRequest;

            localVarRequestOptions.Operation = "CaptacionesVistaApi.DevuelveConsolidadoCuentas";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DevuelveConsolidadoCuentasResponse>("/CaptacionesVista/DevuelveConsolidadoCuentas", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DevuelveConsolidadoCuentas", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveConsolidadoCuentasRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DevuelveConsolidadoCuentasResponse</returns>
        public async System.Threading.Tasks.Task<DevuelveConsolidadoCuentasResponse> DevuelveConsolidadoCuentasAsync(DevuelveConsolidadoCuentasRequest? devuelveConsolidadoCuentasRequest = default(DevuelveConsolidadoCuentasRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Corresponsales.Query.Client.ApiResponse<DevuelveConsolidadoCuentasResponse> localVarResponse = await DevuelveConsolidadoCuentasWithHttpInfoAsync(devuelveConsolidadoCuentasRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveConsolidadoCuentasRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DevuelveConsolidadoCuentasResponse)</returns>
        public async System.Threading.Tasks.Task<Corresponsales.Query.Client.ApiResponse<DevuelveConsolidadoCuentasResponse>> DevuelveConsolidadoCuentasWithHttpInfoAsync(DevuelveConsolidadoCuentasRequest? devuelveConsolidadoCuentasRequest = default(DevuelveConsolidadoCuentasRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Corresponsales.Query.Client.RequestOptions localVarRequestOptions = new Corresponsales.Query.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Corresponsales.Query.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Corresponsales.Query.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = devuelveConsolidadoCuentasRequest;

            localVarRequestOptions.Operation = "CaptacionesVistaApi.DevuelveConsolidadoCuentas";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DevuelveConsolidadoCuentasResponse>("/CaptacionesVista/DevuelveConsolidadoCuentas", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DevuelveConsolidadoCuentas", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveConsolidadoCuentasIdentificacionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DevuelveConsolidadoCuentasIdentificacionResponse</returns>
        public DevuelveConsolidadoCuentasIdentificacionResponse DevuelveConsolidadoCuentasIdentificacion(DevuelveConsolidadoCuentasIdentificacionRequest? devuelveConsolidadoCuentasIdentificacionRequest = default(DevuelveConsolidadoCuentasIdentificacionRequest?), int operationIndex = 0)
        {
            Corresponsales.Query.Client.ApiResponse<DevuelveConsolidadoCuentasIdentificacionResponse> localVarResponse = DevuelveConsolidadoCuentasIdentificacionWithHttpInfo(devuelveConsolidadoCuentasIdentificacionRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveConsolidadoCuentasIdentificacionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DevuelveConsolidadoCuentasIdentificacionResponse</returns>
        public Corresponsales.Query.Client.ApiResponse<DevuelveConsolidadoCuentasIdentificacionResponse> DevuelveConsolidadoCuentasIdentificacionWithHttpInfo(DevuelveConsolidadoCuentasIdentificacionRequest? devuelveConsolidadoCuentasIdentificacionRequest = default(DevuelveConsolidadoCuentasIdentificacionRequest?), int operationIndex = 0)
        {
            Corresponsales.Query.Client.RequestOptions localVarRequestOptions = new Corresponsales.Query.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Corresponsales.Query.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Corresponsales.Query.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = devuelveConsolidadoCuentasIdentificacionRequest;

            localVarRequestOptions.Operation = "CaptacionesVistaApi.DevuelveConsolidadoCuentasIdentificacion";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DevuelveConsolidadoCuentasIdentificacionResponse>("/CaptacionesVista/DevuelveConsolidadoCuentasIdentificacion", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DevuelveConsolidadoCuentasIdentificacion", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveConsolidadoCuentasIdentificacionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DevuelveConsolidadoCuentasIdentificacionResponse</returns>
        public async System.Threading.Tasks.Task<DevuelveConsolidadoCuentasIdentificacionResponse> DevuelveConsolidadoCuentasIdentificacionAsync(DevuelveConsolidadoCuentasIdentificacionRequest? devuelveConsolidadoCuentasIdentificacionRequest = default(DevuelveConsolidadoCuentasIdentificacionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Corresponsales.Query.Client.ApiResponse<DevuelveConsolidadoCuentasIdentificacionResponse> localVarResponse = await DevuelveConsolidadoCuentasIdentificacionWithHttpInfoAsync(devuelveConsolidadoCuentasIdentificacionRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveConsolidadoCuentasIdentificacionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DevuelveConsolidadoCuentasIdentificacionResponse)</returns>
        public async System.Threading.Tasks.Task<Corresponsales.Query.Client.ApiResponse<DevuelveConsolidadoCuentasIdentificacionResponse>> DevuelveConsolidadoCuentasIdentificacionWithHttpInfoAsync(DevuelveConsolidadoCuentasIdentificacionRequest? devuelveConsolidadoCuentasIdentificacionRequest = default(DevuelveConsolidadoCuentasIdentificacionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Corresponsales.Query.Client.RequestOptions localVarRequestOptions = new Corresponsales.Query.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Corresponsales.Query.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Corresponsales.Query.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = devuelveConsolidadoCuentasIdentificacionRequest;

            localVarRequestOptions.Operation = "CaptacionesVistaApi.DevuelveConsolidadoCuentasIdentificacion";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DevuelveConsolidadoCuentasIdentificacionResponse>("/CaptacionesVista/DevuelveConsolidadoCuentasIdentificacion", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DevuelveConsolidadoCuentasIdentificacion", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveCuentaRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DevuelveCuentaResponse</returns>
        public DevuelveCuentaResponse DevuelveCuenta(DevuelveCuentaRequest? devuelveCuentaRequest = default(DevuelveCuentaRequest?), int operationIndex = 0)
        {
            Corresponsales.Query.Client.ApiResponse<DevuelveCuentaResponse> localVarResponse = DevuelveCuentaWithHttpInfo(devuelveCuentaRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveCuentaRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DevuelveCuentaResponse</returns>
        public Corresponsales.Query.Client.ApiResponse<DevuelveCuentaResponse> DevuelveCuentaWithHttpInfo(DevuelveCuentaRequest? devuelveCuentaRequest = default(DevuelveCuentaRequest?), int operationIndex = 0)
        {
            Corresponsales.Query.Client.RequestOptions localVarRequestOptions = new Corresponsales.Query.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Corresponsales.Query.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Corresponsales.Query.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = devuelveCuentaRequest;

            localVarRequestOptions.Operation = "CaptacionesVistaApi.DevuelveCuenta";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DevuelveCuentaResponse>("/CaptacionesVista/DevuelveCuenta", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DevuelveCuenta", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveCuentaRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DevuelveCuentaResponse</returns>
        public async System.Threading.Tasks.Task<DevuelveCuentaResponse> DevuelveCuentaAsync(DevuelveCuentaRequest? devuelveCuentaRequest = default(DevuelveCuentaRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Corresponsales.Query.Client.ApiResponse<DevuelveCuentaResponse> localVarResponse = await DevuelveCuentaWithHttpInfoAsync(devuelveCuentaRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveCuentaRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DevuelveCuentaResponse)</returns>
        public async System.Threading.Tasks.Task<Corresponsales.Query.Client.ApiResponse<DevuelveCuentaResponse>> DevuelveCuentaWithHttpInfoAsync(DevuelveCuentaRequest? devuelveCuentaRequest = default(DevuelveCuentaRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Corresponsales.Query.Client.RequestOptions localVarRequestOptions = new Corresponsales.Query.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Corresponsales.Query.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Corresponsales.Query.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = devuelveCuentaRequest;

            localVarRequestOptions.Operation = "CaptacionesVistaApi.DevuelveCuenta";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DevuelveCuentaResponse>("/CaptacionesVista/DevuelveCuenta", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DevuelveCuenta", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveTiposDeCuentasDeUnClienteRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DevuelveTiposDeCuentasDeUnClienteResponse</returns>
        public DevuelveTiposDeCuentasDeUnClienteResponse DevuelveTiposDeCuentasDeUnCliente(DevuelveTiposDeCuentasDeUnClienteRequest? devuelveTiposDeCuentasDeUnClienteRequest = default(DevuelveTiposDeCuentasDeUnClienteRequest?), int operationIndex = 0)
        {
            Corresponsales.Query.Client.ApiResponse<DevuelveTiposDeCuentasDeUnClienteResponse> localVarResponse = DevuelveTiposDeCuentasDeUnClienteWithHttpInfo(devuelveTiposDeCuentasDeUnClienteRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveTiposDeCuentasDeUnClienteRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DevuelveTiposDeCuentasDeUnClienteResponse</returns>
        public Corresponsales.Query.Client.ApiResponse<DevuelveTiposDeCuentasDeUnClienteResponse> DevuelveTiposDeCuentasDeUnClienteWithHttpInfo(DevuelveTiposDeCuentasDeUnClienteRequest? devuelveTiposDeCuentasDeUnClienteRequest = default(DevuelveTiposDeCuentasDeUnClienteRequest?), int operationIndex = 0)
        {
            Corresponsales.Query.Client.RequestOptions localVarRequestOptions = new Corresponsales.Query.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Corresponsales.Query.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Corresponsales.Query.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = devuelveTiposDeCuentasDeUnClienteRequest;

            localVarRequestOptions.Operation = "CaptacionesVistaApi.DevuelveTiposDeCuentasDeUnCliente";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DevuelveTiposDeCuentasDeUnClienteResponse>("/CaptacionesVista/DevuelveTiposDeCuentasDeUnCliente", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DevuelveTiposDeCuentasDeUnCliente", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveTiposDeCuentasDeUnClienteRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DevuelveTiposDeCuentasDeUnClienteResponse</returns>
        public async System.Threading.Tasks.Task<DevuelveTiposDeCuentasDeUnClienteResponse> DevuelveTiposDeCuentasDeUnClienteAsync(DevuelveTiposDeCuentasDeUnClienteRequest? devuelveTiposDeCuentasDeUnClienteRequest = default(DevuelveTiposDeCuentasDeUnClienteRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Corresponsales.Query.Client.ApiResponse<DevuelveTiposDeCuentasDeUnClienteResponse> localVarResponse = await DevuelveTiposDeCuentasDeUnClienteWithHttpInfoAsync(devuelveTiposDeCuentasDeUnClienteRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="devuelveTiposDeCuentasDeUnClienteRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DevuelveTiposDeCuentasDeUnClienteResponse)</returns>
        public async System.Threading.Tasks.Task<Corresponsales.Query.Client.ApiResponse<DevuelveTiposDeCuentasDeUnClienteResponse>> DevuelveTiposDeCuentasDeUnClienteWithHttpInfoAsync(DevuelveTiposDeCuentasDeUnClienteRequest? devuelveTiposDeCuentasDeUnClienteRequest = default(DevuelveTiposDeCuentasDeUnClienteRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Corresponsales.Query.Client.RequestOptions localVarRequestOptions = new Corresponsales.Query.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Corresponsales.Query.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Corresponsales.Query.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = devuelveTiposDeCuentasDeUnClienteRequest;

            localVarRequestOptions.Operation = "CaptacionesVistaApi.DevuelveTiposDeCuentasDeUnCliente";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DevuelveTiposDeCuentasDeUnClienteResponse>("/CaptacionesVista/DevuelveTiposDeCuentasDeUnCliente", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DevuelveTiposDeCuentasDeUnCliente", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
