/*
 * Corresponsales.Query.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Corresponsales.Query.Client;
using Corresponsales.Query.Model;

namespace Corresponsales.Query.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFacilitoApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consultaValorAPagarRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ConsultaValorAPagarResponse</returns>
        ConsultaValorAPagarResponse ConsultaValorAPagar(ConsultaValorAPagarRequest? consultaValorAPagarRequest = default(ConsultaValorAPagarRequest?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consultaValorAPagarRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ConsultaValorAPagarResponse</returns>
        ApiResponse<ConsultaValorAPagarResponse> ConsultaValorAPagarWithHttpInfo(ConsultaValorAPagarRequest? consultaValorAPagarRequest = default(ConsultaValorAPagarRequest?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="obtenerProductosRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ObtenerProductosResponse</returns>
        ObtenerProductosResponse ObtenerProductos(ObtenerProductosRequest? obtenerProductosRequest = default(ObtenerProductosRequest?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="obtenerProductosRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ObtenerProductosResponse</returns>
        ApiResponse<ObtenerProductosResponse> ObtenerProductosWithHttpInfo(ObtenerProductosRequest? obtenerProductosRequest = default(ObtenerProductosRequest?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ObtenerServiciosResponse</returns>
        ObtenerServiciosResponse ObtenerServicios(int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ObtenerServiciosResponse</returns>
        ApiResponse<ObtenerServiciosResponse> ObtenerServiciosWithHttpInfo(int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFacilitoApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consultaValorAPagarRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConsultaValorAPagarResponse</returns>
        System.Threading.Tasks.Task<ConsultaValorAPagarResponse> ConsultaValorAPagarAsync(ConsultaValorAPagarRequest? consultaValorAPagarRequest = default(ConsultaValorAPagarRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consultaValorAPagarRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConsultaValorAPagarResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ConsultaValorAPagarResponse>> ConsultaValorAPagarWithHttpInfoAsync(ConsultaValorAPagarRequest? consultaValorAPagarRequest = default(ConsultaValorAPagarRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="obtenerProductosRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ObtenerProductosResponse</returns>
        System.Threading.Tasks.Task<ObtenerProductosResponse> ObtenerProductosAsync(ObtenerProductosRequest? obtenerProductosRequest = default(ObtenerProductosRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="obtenerProductosRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ObtenerProductosResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ObtenerProductosResponse>> ObtenerProductosWithHttpInfoAsync(ObtenerProductosRequest? obtenerProductosRequest = default(ObtenerProductosRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ObtenerServiciosResponse</returns>
        System.Threading.Tasks.Task<ObtenerServiciosResponse> ObtenerServiciosAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ObtenerServiciosResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ObtenerServiciosResponse>> ObtenerServiciosWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFacilitoApi : IFacilitoApiSync, IFacilitoApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class FacilitoApi : IFacilitoApi
    {
        private Corresponsales.Query.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="FacilitoApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FacilitoApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FacilitoApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FacilitoApi(string basePath)
        {
            this.Configuration = Corresponsales.Query.Client.Configuration.MergeConfigurations(
                Corresponsales.Query.Client.GlobalConfiguration.Instance,
                new Corresponsales.Query.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Corresponsales.Query.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Corresponsales.Query.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Corresponsales.Query.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FacilitoApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public FacilitoApi(Corresponsales.Query.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Corresponsales.Query.Client.Configuration.MergeConfigurations(
                Corresponsales.Query.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Corresponsales.Query.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Corresponsales.Query.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Corresponsales.Query.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FacilitoApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public FacilitoApi(Corresponsales.Query.Client.ISynchronousClient client, Corresponsales.Query.Client.IAsynchronousClient asyncClient, Corresponsales.Query.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Corresponsales.Query.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Corresponsales.Query.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Corresponsales.Query.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Corresponsales.Query.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Corresponsales.Query.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consultaValorAPagarRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ConsultaValorAPagarResponse</returns>
        public ConsultaValorAPagarResponse ConsultaValorAPagar(ConsultaValorAPagarRequest? consultaValorAPagarRequest = default(ConsultaValorAPagarRequest?), int operationIndex = 0)
        {
            Corresponsales.Query.Client.ApiResponse<ConsultaValorAPagarResponse> localVarResponse = ConsultaValorAPagarWithHttpInfo(consultaValorAPagarRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consultaValorAPagarRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ConsultaValorAPagarResponse</returns>
        public Corresponsales.Query.Client.ApiResponse<ConsultaValorAPagarResponse> ConsultaValorAPagarWithHttpInfo(ConsultaValorAPagarRequest? consultaValorAPagarRequest = default(ConsultaValorAPagarRequest?), int operationIndex = 0)
        {
            Corresponsales.Query.Client.RequestOptions localVarRequestOptions = new Corresponsales.Query.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Corresponsales.Query.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Corresponsales.Query.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = consultaValorAPagarRequest;

            localVarRequestOptions.Operation = "FacilitoApi.ConsultaValorAPagar";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ConsultaValorAPagarResponse>("/Facilito/ConsultaValorAPagar", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ConsultaValorAPagar", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consultaValorAPagarRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConsultaValorAPagarResponse</returns>
        public async System.Threading.Tasks.Task<ConsultaValorAPagarResponse> ConsultaValorAPagarAsync(ConsultaValorAPagarRequest? consultaValorAPagarRequest = default(ConsultaValorAPagarRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Corresponsales.Query.Client.ApiResponse<ConsultaValorAPagarResponse> localVarResponse = await ConsultaValorAPagarWithHttpInfoAsync(consultaValorAPagarRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consultaValorAPagarRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConsultaValorAPagarResponse)</returns>
        public async System.Threading.Tasks.Task<Corresponsales.Query.Client.ApiResponse<ConsultaValorAPagarResponse>> ConsultaValorAPagarWithHttpInfoAsync(ConsultaValorAPagarRequest? consultaValorAPagarRequest = default(ConsultaValorAPagarRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Corresponsales.Query.Client.RequestOptions localVarRequestOptions = new Corresponsales.Query.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Corresponsales.Query.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Corresponsales.Query.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = consultaValorAPagarRequest;

            localVarRequestOptions.Operation = "FacilitoApi.ConsultaValorAPagar";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<ConsultaValorAPagarResponse>("/Facilito/ConsultaValorAPagar", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ConsultaValorAPagar", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="obtenerProductosRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ObtenerProductosResponse</returns>
        public ObtenerProductosResponse ObtenerProductos(ObtenerProductosRequest? obtenerProductosRequest = default(ObtenerProductosRequest?), int operationIndex = 0)
        {
            Corresponsales.Query.Client.ApiResponse<ObtenerProductosResponse> localVarResponse = ObtenerProductosWithHttpInfo(obtenerProductosRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="obtenerProductosRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ObtenerProductosResponse</returns>
        public Corresponsales.Query.Client.ApiResponse<ObtenerProductosResponse> ObtenerProductosWithHttpInfo(ObtenerProductosRequest? obtenerProductosRequest = default(ObtenerProductosRequest?), int operationIndex = 0)
        {
            Corresponsales.Query.Client.RequestOptions localVarRequestOptions = new Corresponsales.Query.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Corresponsales.Query.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Corresponsales.Query.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = obtenerProductosRequest;

            localVarRequestOptions.Operation = "FacilitoApi.ObtenerProductos";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ObtenerProductosResponse>("/Facilito/ObtenerProductos", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ObtenerProductos", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="obtenerProductosRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ObtenerProductosResponse</returns>
        public async System.Threading.Tasks.Task<ObtenerProductosResponse> ObtenerProductosAsync(ObtenerProductosRequest? obtenerProductosRequest = default(ObtenerProductosRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Corresponsales.Query.Client.ApiResponse<ObtenerProductosResponse> localVarResponse = await ObtenerProductosWithHttpInfoAsync(obtenerProductosRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="obtenerProductosRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ObtenerProductosResponse)</returns>
        public async System.Threading.Tasks.Task<Corresponsales.Query.Client.ApiResponse<ObtenerProductosResponse>> ObtenerProductosWithHttpInfoAsync(ObtenerProductosRequest? obtenerProductosRequest = default(ObtenerProductosRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Corresponsales.Query.Client.RequestOptions localVarRequestOptions = new Corresponsales.Query.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Corresponsales.Query.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Corresponsales.Query.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = obtenerProductosRequest;

            localVarRequestOptions.Operation = "FacilitoApi.ObtenerProductos";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<ObtenerProductosResponse>("/Facilito/ObtenerProductos", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ObtenerProductos", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ObtenerServiciosResponse</returns>
        public ObtenerServiciosResponse ObtenerServicios(int operationIndex = 0)
        {
            Corresponsales.Query.Client.ApiResponse<ObtenerServiciosResponse> localVarResponse = ObtenerServiciosWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ObtenerServiciosResponse</returns>
        public Corresponsales.Query.Client.ApiResponse<ObtenerServiciosResponse> ObtenerServiciosWithHttpInfo(int operationIndex = 0)
        {
            Corresponsales.Query.Client.RequestOptions localVarRequestOptions = new Corresponsales.Query.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Corresponsales.Query.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Corresponsales.Query.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "FacilitoApi.ObtenerServicios";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ObtenerServiciosResponse>("/Facilito/ObtenerServicios", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ObtenerServicios", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ObtenerServiciosResponse</returns>
        public async System.Threading.Tasks.Task<ObtenerServiciosResponse> ObtenerServiciosAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Corresponsales.Query.Client.ApiResponse<ObtenerServiciosResponse> localVarResponse = await ObtenerServiciosWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Corresponsales.Query.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ObtenerServiciosResponse)</returns>
        public async System.Threading.Tasks.Task<Corresponsales.Query.Client.ApiResponse<ObtenerServiciosResponse>> ObtenerServiciosWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Corresponsales.Query.Client.RequestOptions localVarRequestOptions = new Corresponsales.Query.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Corresponsales.Query.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Corresponsales.Query.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "FacilitoApi.ObtenerServicios";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<ObtenerServiciosResponse>("/Facilito/ObtenerServicios", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ObtenerServicios", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
