<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="FBS_Core.Identity.Domain.Models">
      <HintPath>..\..\..\FBS_Core\FBS_Core.Identity.Domain.Services\bin\Debug\netcoreapp2.2\FBS_Core.Identity.Domain.Models.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
