// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Afectacion.
    /// </summary>
    public static partial class AfectacionExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            public static AfectacionAUnCorresponsalMS AfectacionAUnCorresponsal(this IAfectacion operations, AfectacionAUnCorresponsalME request)
            {
                return operations.AfectacionAUnCorresponsalAsync(request).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<AfectacionAUnCorresponsalMS> AfectacionAUnCorresponsalAsync(this IAfectacion operations, AfectacionAUnCorresponsalME request, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.AfectacionAUnCorresponsalWithHttpMessagesAsync(request, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            public static PagoFacilitoMS PagoFacilito(this IAfectacion operations, PagoFacilitoME request)
            {
                return operations.PagoFacilitoAsync(request).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<PagoFacilitoMS> PagoFacilitoAsync(this IAfectacion operations, PagoFacilitoME request, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PagoFacilitoWithHttpMessagesAsync(request, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
