// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Cuentas.
    /// </summary>
    public static partial class CuentasExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            public static ConsolidadoCuentasMSL DevuelveConsolidadoCuentas(this ICuentas operations, PorClienteDeUnaEmpresaME request)
            {
                return operations.DevuelveConsolidadoCuentasAsync(request).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ConsolidadoCuentasMSL> DevuelveConsolidadoCuentasAsync(this ICuentas operations, PorClienteDeUnaEmpresaME request, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.DevuelveConsolidadoCuentasWithHttpMessagesAsync(request, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            public static TiposCuentaClienteMSL DevuelveTiposDeCuentasDeUnCliente(this ICuentas operations, PorSecuencialClienteDeUnaEmpresaProductoVista request)
            {
                return operations.DevuelveTiposDeCuentasDeUnClienteAsync(request).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<TiposCuentaClienteMSL> DevuelveTiposDeCuentasDeUnClienteAsync(this ICuentas operations, PorSecuencialClienteDeUnaEmpresaProductoVista request, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.DevuelveTiposDeCuentasDeUnClienteWithHttpMessagesAsync(request, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            public static RespuestaProcesoDepositoMS ProcesaDeposito(this ICuentas operations, PedidoDatosTransaccionDepositoME request)
            {
                return operations.ProcesaDepositoAsync(request).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<RespuestaProcesoDepositoMS> ProcesaDepositoAsync(this ICuentas operations, PedidoDatosTransaccionDepositoME request, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ProcesaDepositoWithHttpMessagesAsync(request, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            public static RespuestaProcesoRetiroMS ProcesaRetiro(this ICuentas operations, PedidoDatosTransaccionRetiroME request)
            {
                return operations.ProcesaRetiroAsync(request).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<RespuestaProcesoRetiroMS> ProcesaRetiroAsync(this ICuentas operations, PedidoDatosTransaccionRetiroME request, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ProcesaRetiroWithHttpMessagesAsync(request, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            public static CreaCuentaMS CreaCuenta(this ICuentas operations, CreaCuentaME request)
            {
                return operations.CreaCuentaAsync(request).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<CreaCuentaMS> CreaCuentaAsync(this ICuentas operations, CreaCuentaME request, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreaCuentaWithHttpMessagesAsync(request, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
