// <auto-generated />
using System;
using FBSConsolaCBWebApi.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FBSConsolaCBWebApi.WebApi.Migrations
{
    [DbContext(typeof(ContextoFBSConsolaCB))]
    [Migration("20200516134459_Fix_TipoIdentificacionAgente")]
    partial class Fix_TipoIdentificacionAgente
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FBS.DAL.Nomenclador.Catalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrencia")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Descripcion");

                    b.Property<bool>("EstaActivo");

                    b.Property<string>("Nombre");

                    b.Property<Guid?>("TipoCatalogoId");

                    b.HasKey("Id");

                    b.HasIndex("TipoCatalogoId");

                    b.ToTable("Catalogo","Nomenclador");
                });

            modelBuilder.Entity("FBS.DAL.Nomenclador.TipoCatalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrencia")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Descripcion");

                    b.Property<bool>("EstaActivo");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoCatalogo","Nomenclador");
                });

            modelBuilder.Entity("FBS.Identidad.DAL.Seguridad.Canal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrencia")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<bool>("EstaActivo");

                    b.Property<string>("JsonConfiguracion");

                    b.Property<string>("JsonNegocio");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Canal","Seguridad");
                });

            modelBuilder.Entity("FBS.Identidad.DAL.Seguridad.CanalUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CanalId");

                    b.Property<byte[]>("Concurrencia")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<bool>("EstaActivo");

                    b.Property<string>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("CanalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CanalUsuario","Seguridad");
                });

            modelBuilder.Entity("FBS.Identidad.DAL.Seguridad.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrencia")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<bool>("EstaActivo");

                    b.Property<string>("Icono");

                    b.Property<Guid?>("MenuId")
                        .HasColumnName("MenuPadreId");

                    b.Property<string>("Nombre");

                    b.Property<int>("Orden");

                    b.Property<string>("Ruta");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("Menu","Seguridad");
                });

            modelBuilder.Entity("FBS.Identidad.DAL.Seguridad.Rol", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnName("Concurrencia");

                    b.Property<string>("Descripcion")
                        .HasColumnName("Descripcion")
                        .HasMaxLength(256);

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EstaActivo")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .HasColumnName("Nombre")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnName("NombreNormalizado")
                        .HasMaxLength(256);

                    b.Property<bool>("Type")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NombreNormalizado] IS NOT NULL");

                    b.ToTable("Rol","Seguridad");
                });

            modelBuilder.Entity("FBS.Identidad.DAL.Seguridad.RolMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrencia")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<bool>("EstaActivo");

                    b.Property<Guid?>("MenuId");

                    b.Property<string>("RolId");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RolId");

                    b.ToTable("RolMenu","Seguridad");
                });

            modelBuilder.Entity("FBS.Identidad.DAL.Seguridad.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnName("AccesosFallidos");

                    b.Property<bool>("CambioContrasenia")
                        .HasColumnName("CambioContrasenia");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnName("Concurrencia");

                    b.Property<string>("Email")
                        .HasColumnName("CorreoElectronico")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnName("CorreoElectronicoConfirmado");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EstaActivo")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Imagen")
                        .HasColumnName("Imagen")
                        .HasMaxLength(256);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnName("BloqueoActivo");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnName("FinBloqueo");

                    b.Property<string>("NombreCompleto")
                        .HasColumnName("NombreCompleto")
                        .HasMaxLength(256);

                    b.Property<string>("NombreMostrar")
                        .HasColumnName("NombreMostrar")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedEmail")
                        .HasColumnName("CorreoElectronicoNormalizado")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnName("CodigoNormalizado")
                        .HasMaxLength(256);

                    b.Property<Guid?>("OperadoraId");

                    b.Property<string>("PasswordHash")
                        .HasColumnName("Contrasenia");

                    b.Property<string>("PhoneNumber")
                        .HasColumnName("TelefonoCelular");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnName("TelefonoConfirmado");

                    b.Property<string>("SecurityStamp")
                        .HasColumnName("MarcaSeguridad");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnName("DobleVerificacion");

                    b.Property<string>("UserName")
                        .HasColumnName("Codigo")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[CodigoNormalizado] IS NOT NULL");

                    b.HasIndex("OperadoraId");

                    b.ToTable("Usuario","Seguridad");
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Canales.AgenteGeolocalizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AgenteId");

                    b.Property<byte[]>("Concurrencia")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<bool>("EstaActivo");

                    b.Property<Guid?>("GeolocalizacionId");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("GeolocalizacionId");

                    b.ToTable("AgenteGeolocalizacion","Canales");
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Canales.Dispositivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrencia")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("DireccionImpresora");

                    b.Property<bool>("EstaActivo");

                    b.Property<string>("Imei");

                    b.Property<string>("MacAddress");

                    b.Property<Guid?>("MarcaId");

                    b.Property<string>("Modelo");

                    b.Property<string>("NumeroSerie");

                    b.Property<string>("Observaciones");

                    b.Property<Guid?>("SistemaOperativoId");

                    b.Property<bool>("TieneImpresora");

                    b.Property<string>("Ubicacion");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.HasIndex("SistemaOperativoId");

                    b.ToTable("Dispositivo","Canales");
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Canales.Geolocalizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrencia")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<bool>("EstaActivo");

                    b.Property<DateTime>("FechaAlta");

                    b.Property<DateTime>("FechaBaja");

                    b.Property<double>("Latitud");

                    b.Property<double>("Longitud");

                    b.HasKey("Id");

                    b.ToTable("Geolocalizacion","Canales");
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Canales.Imagen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrencia")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("DireccionImagen");

                    b.Property<Guid?>("DispositivoId");

                    b.Property<bool>("EstaActivo");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoId");

                    b.ToTable("Imagen","Canales");
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Canales.ImagenGeolocalizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrencia")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("DireccionImagen");

                    b.Property<bool>("EstaActivo");

                    b.Property<Guid?>("GeolocalizacionId");

                    b.HasKey("Id");

                    b.HasIndex("GeolocalizacionId");

                    b.ToTable("ImagenGeolocalizacion","Canales");
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Canales.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrencia")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Criptografia");

                    b.Property<bool>("EstaActivo");

                    b.Property<Guid?>("EstadoId");

                    b.Property<DateTime>("Fecha");

                    b.Property<TimeSpan>("Hora");

                    b.Property<string>("JsonDispositivo");

                    b.Property<string>("JsonLog");

                    b.Property<string>("RelacionadoId");

                    b.Property<Guid?>("TipoAccionId");

                    b.Property<string>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("TipoAccionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Log","Canales");
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Corresponsales.Agente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrencia")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<Guid?>("DispositivoId");

                    b.Property<bool>("EstaActivo");

                    b.Property<Guid?>("EstadoId");

                    b.Property<string>("Identificacion");

                    b.Property<string>("JsonAgente");

                    b.Property<string>("NombreAgente");

                    b.Property<string>("SupervisorId");

                    b.Property<int>("TipoIdentificacion");

                    b.Property<string>("Ubicacion");

                    b.Property<string>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Agente","Corresponsales");
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Corresponsales.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AgenteId");

                    b.Property<string>("Comentario");

                    b.Property<byte[]>("Concurrencia")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Descripcion");

                    b.Property<bool>("EstaActivo");

                    b.Property<Guid?>("EstadoId");

                    b.Property<DateTime>("Fecha");

                    b.Property<TimeSpan>("Hora");

                    b.Property<Guid?>("TipoId");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("TipoId");

                    b.ToTable("Alerta","Corresponsales");
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Corresponsales.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AgenteId");

                    b.Property<byte[]>("Concurrencia")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<bool>("EstaActivo");

                    b.Property<string>("NumeroCuenta");

                    b.Property<string>("SecuencialCuenta");

                    b.Property<string>("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.ToTable("Cuenta","Corresponsales");
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Corresponsales.Transaccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AgenteId");

                    b.Property<string>("CanalId");

                    b.Property<string>("Comisiones");

                    b.Property<byte[]>("Concurrencia")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Criptografia");

                    b.Property<string>("Descripcion");

                    b.Property<bool>("EstaActivo");

                    b.Property<Guid?>("EstadoId");

                    b.Property<DateTime>("FechaDispositivo");

                    b.Property<DateTime>("FechaSistema");

                    b.Property<TimeSpan>("HoraDispositivo");

                    b.Property<string>("IdentificacionCliente");

                    b.Property<string>("JsonDatos");

                    b.Property<string>("NombreCliente");

                    b.Property<bool>("ReposicionRealizada");

                    b.Property<double>("SaldoCuenta");

                    b.Property<double>("SaldoDisponible");

                    b.Property<string>("SecuencialCuenta");

                    b.Property<string>("Tipo");

                    b.Property<double>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("EstadoId");

                    b.ToTable("Transaccion","Corresponsales");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnName("Tipo");

                    b.Property<string>("ClaimValue")
                        .HasColumnName("Valor");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnName("RolId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RolPermiso","Seguridad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnName("Tipo");

                    b.Property<string>("ClaimValue")
                        .HasColumnName("Valor");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsuarioPermiso","Seguridad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnName("Proveedor");

                    b.Property<string>("ProviderKey")
                        .HasColumnName("LlaveProveedor");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnName("NombreProveedor");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnName("UsuarioId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AutenticacionUsuario","Seguridad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnName("UsuarioId");

                    b.Property<string>("RoleId")
                        .HasColumnName("RolId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuarioRol","Seguridad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnName("UsuarioId");

                    b.Property<string>("LoginProvider")
                        .HasColumnName("Proveedor");

                    b.Property<string>("Name")
                        .HasColumnName("Nombre");

                    b.Property<string>("Value")
                        .HasColumnName("Valor");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UsuarioToken","Seguridad");
                });

            modelBuilder.Entity("FBS.DAL.Nomenclador.Catalogo", b =>
                {
                    b.HasOne("FBS.DAL.Nomenclador.TipoCatalogo", "TipoCatalogo")
                        .WithMany("Catalogos")
                        .HasForeignKey("TipoCatalogoId");
                });

            modelBuilder.Entity("FBS.Identidad.DAL.Seguridad.CanalUsuario", b =>
                {
                    b.HasOne("FBS.Identidad.DAL.Seguridad.Canal", "Canal")
                        .WithMany()
                        .HasForeignKey("CanalId");

                    b.HasOne("FBS.Identidad.DAL.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("FBS.Identidad.DAL.Seguridad.Menu", b =>
                {
                    b.HasOne("FBS.Identidad.DAL.Seguridad.Menu")
                        .WithMany("Menus")
                        .HasForeignKey("MenuId");
                });

            modelBuilder.Entity("FBS.Identidad.DAL.Seguridad.RolMenu", b =>
                {
                    b.HasOne("FBS.Identidad.DAL.Seguridad.Menu", "Menu")
                        .WithMany("RoleMenu")
                        .HasForeignKey("MenuId");

                    b.HasOne("FBS.Identidad.DAL.Seguridad.Rol", "Rol")
                        .WithMany("RoleMenu")
                        .HasForeignKey("RolId");
                });

            modelBuilder.Entity("FBS.Identidad.DAL.Seguridad.Usuario", b =>
                {
                    b.HasOne("FBS.DAL.Nomenclador.Catalogo", "Operadora")
                        .WithMany()
                        .HasForeignKey("OperadoraId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Canales.AgenteGeolocalizacion", b =>
                {
                    b.HasOne("FBSConsolaCBWebApi.DAL.Corresponsales.Agente", "Agente")
                        .WithMany()
                        .HasForeignKey("AgenteId");

                    b.HasOne("FBSConsolaCBWebApi.DAL.Canales.Geolocalizacion", "Geolocalizacion")
                        .WithMany()
                        .HasForeignKey("GeolocalizacionId");
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Canales.Dispositivo", b =>
                {
                    b.HasOne("FBS.DAL.Nomenclador.Catalogo", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId");

                    b.HasOne("FBS.DAL.Nomenclador.Catalogo", "SistemaOperativo")
                        .WithMany()
                        .HasForeignKey("SistemaOperativoId");
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Canales.Imagen", b =>
                {
                    b.HasOne("FBSConsolaCBWebApi.DAL.Canales.Dispositivo", "Dispositivo")
                        .WithMany()
                        .HasForeignKey("DispositivoId");
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Canales.ImagenGeolocalizacion", b =>
                {
                    b.HasOne("FBSConsolaCBWebApi.DAL.Canales.Geolocalizacion", "Geolocalizacion")
                        .WithMany()
                        .HasForeignKey("GeolocalizacionId");
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Canales.Log", b =>
                {
                    b.HasOne("FBS.DAL.Nomenclador.Catalogo", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId");

                    b.HasOne("FBS.DAL.Nomenclador.Catalogo", "TipoAccion")
                        .WithMany()
                        .HasForeignKey("TipoAccionId");

                    b.HasOne("FBS.Identidad.DAL.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Corresponsales.Agente", b =>
                {
                    b.HasOne("FBSConsolaCBWebApi.DAL.Canales.Dispositivo", "Dispositivo")
                        .WithMany()
                        .HasForeignKey("DispositivoId");

                    b.HasOne("FBS.DAL.Nomenclador.Catalogo", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId");

                    b.HasOne("FBS.Identidad.DAL.Seguridad.Usuario", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId");

                    b.HasOne("FBS.Identidad.DAL.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Corresponsales.Alerta", b =>
                {
                    b.HasOne("FBSConsolaCBWebApi.DAL.Corresponsales.Agente", "Agente")
                        .WithMany()
                        .HasForeignKey("AgenteId");

                    b.HasOne("FBS.DAL.Nomenclador.Catalogo", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId");

                    b.HasOne("FBS.DAL.Nomenclador.Catalogo", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId");
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Corresponsales.Cuenta", b =>
                {
                    b.HasOne("FBSConsolaCBWebApi.DAL.Corresponsales.Agente", "Agente")
                        .WithMany()
                        .HasForeignKey("AgenteId");
                });

            modelBuilder.Entity("FBSConsolaCBWebApi.DAL.Corresponsales.Transaccion", b =>
                {
                    b.HasOne("FBSConsolaCBWebApi.DAL.Corresponsales.Agente", "Agente")
                        .WithMany()
                        .HasForeignKey("AgenteId");

                    b.HasOne("FBS.DAL.Nomenclador.Catalogo", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("FBS.Identidad.DAL.Seguridad.Rol")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FBS.Identidad.DAL.Seguridad.Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FBS.Identidad.DAL.Seguridad.Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("FBS.Identidad.DAL.Seguridad.Rol")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FBS.Identidad.DAL.Seguridad.Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FBS.Identidad.DAL.Seguridad.Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
