<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="FBS.DAL">
      <HintPath>..\..\..\FBS_Core\FBS.DAL\bin\Debug\netcoreapp2.2\FBS.DAL.dll</HintPath>
    </Reference>
    <Reference Include="FBS.Identidad.DAL">
      <HintPath>..\..\..\FBS_Core\FBS.Identidad.DAL\bin\Debug\netcoreapp2.2\FBS.Identidad.DAL.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
