<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FBSConsolaCB_WebApi.DAL\FBSConsolaCB_WebApi.DAL.csproj" />
    <ProjectReference Include="..\FBS_Core\FBS.Infraestructura\FBS.Infraestructura.csproj" />
  </ItemGroup>

</Project>
