<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FBSConsolaCB_WebApi.DAL\FBSConsolaCB_WebApi.DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="FBS.Identidad.DAL">
      <HintPath>..\..\..\FBS_Core\FBS.Identidad.DAL\bin\Debug\netcoreapp2.2\FBS.Identidad.DAL.dll</HintPath>
    </Reference>
    <Reference Include="FBS.Infraestructura">
      <HintPath>..\..\..\FBS_Core\FBS.Infraestructura\bin\Debug\netcoreapp2.2\FBS.Infraestructura.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
