// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosTulcan
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Clientes.
    /// </summary>
    public static partial class ClientesExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='porIdentificacionSocioME'>
            /// </param>
            public static object DevuelveDatosPersonaIdentificacion(this IClientes operations, ClPorIdentificacionSocioME porIdentificacionSocioME)
            {
                return operations.DevuelveDatosPersonaIdentificacionAsync(porIdentificacionSocioME).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='porIdentificacionSocioME'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> DevuelveDatosPersonaIdentificacionAsync(this IClientes operations, ClPorIdentificacionSocioME porIdentificacionSocioME, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.DevuelveDatosPersonaIdentificacionWithHttpMessagesAsync(porIdentificacionSocioME, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='creaClienteME'>
            /// </param>
            public static bool? CreaCliente(this IClientes operations, ClCreaClienteME creaClienteME)
            {
                return operations.CreaClienteAsync(creaClienteME).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='creaClienteME'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<bool?> CreaClienteAsync(this IClientes operations, ClCreaClienteME creaClienteME, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreaClienteWithHttpMessagesAsync(creaClienteME, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static object DevuelveTiposIdentificacion(this IClientes operations)
            {
                return operations.DevuelveTiposIdentificacionAsync().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> DevuelveTiposIdentificacionAsync(this IClientes operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.DevuelveTiposIdentificacionWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='porCodigoUsuarioCorresponsalME'>
            /// </param>
            public static bool? CreaUsuario(this IClientes operations, ClPorCodigoUsuarioCorresponsalME porCodigoUsuarioCorresponsalME)
            {
                return operations.CreaUsuarioAsync(porCodigoUsuarioCorresponsalME).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='porCodigoUsuarioCorresponsalME'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<bool?> CreaUsuarioAsync(this IClientes operations, ClPorCodigoUsuarioCorresponsalME porCodigoUsuarioCorresponsalME, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreaUsuarioWithHttpMessagesAsync(porCodigoUsuarioCorresponsalME, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='actualizaEstadoUsuarioME'>
            /// </param>
            public static bool? ActualizaEstadoUsuario(this IClientes operations, ClActualizaEstadoUsuarioME actualizaEstadoUsuarioME)
            {
                return operations.ActualizaEstadoUsuarioAsync(actualizaEstadoUsuarioME).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='actualizaEstadoUsuarioME'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<bool?> ActualizaEstadoUsuarioAsync(this IClientes operations, ClActualizaEstadoUsuarioME actualizaEstadoUsuarioME, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ActualizaEstadoUsuarioWithHttpMessagesAsync(actualizaEstadoUsuarioME, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
