/*
 * FBSCorresponsalesApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// EnvioSMSME
    /// </summary>
    [DataContract(Name = "EnvioSMSME")]
    public partial class EnvioSMSME : IEquatable<EnvioSMSME>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EnvioSMSME" /> class.
        /// </summary>
        /// <param name="secuencialTipoIdentificacion">secuencialTipoIdentificacion.</param>
        /// <param name="numeroIdentificacion">numeroIdentificacion.</param>
        /// <param name="codigoUsuarioCorresponsal">codigoUsuarioCorresponsal.</param>
        /// <param name="mensajeTexto">mensajeTexto.</param>
        /// <param name="numerocelular">numeroCelular.</param>
        public EnvioSMSME(int secuencialTipoIdentificacion = default(int), string numeroIdentificacion = default(string), string codigoUsuarioCorresponsal = default(string), string mensajeTexto = default(string), string numerocelular = default(string))
        {
            this.SecuencialTipoIdentificacion = secuencialTipoIdentificacion;
            this.NumeroIdentificacion = numeroIdentificacion;
            this.CodigoUsuarioCorresponsal = codigoUsuarioCorresponsal;
            this.MensajeTexto = mensajeTexto;
            this.NumeroCelular = numerocelular;
        }

        /// <summary>
        /// Gets or Sets SecuencialTipoIdentificacion
        /// </summary>
        [DataMember(Name = "SecuencialTipoIdentificacion", EmitDefaultValue = false)]
        public int SecuencialTipoIdentificacion { get; set; }

        /// <summary>
        /// Gets or Sets NumeroIdentificacion
        /// </summary>
        [DataMember(Name = "NumeroIdentificacion", EmitDefaultValue = false)]
        public string NumeroIdentificacion { get; set; }

        /// <summary>
        /// Gets or Sets CodigoUsuarioCorresponsal
        /// </summary>
        [DataMember(Name = "CodigoUsuarioCorresponsal", EmitDefaultValue = false)]
        public string CodigoUsuarioCorresponsal { get; set; }

        /// <summary>
        /// Gets or Sets MensajeTexto
        /// </summary>
        [DataMember(Name = "MensajeTexto", EmitDefaultValue = false)]
        public string MensajeTexto { get; set; }

        /// <summary>
        /// Gets or Sets NumeroCelular
        /// </summary>
        [DataMember(Name = "NumeroCelular", EmitDefaultValue = false)]
        public string NumeroCelular { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EnvioSMSME {\n");
            sb.Append("  SecuencialTipoIdentificacion: ").Append(SecuencialTipoIdentificacion).Append("\n");
            sb.Append("  NumeroIdentificacion: ").Append(NumeroIdentificacion).Append("\n");
            sb.Append("  CodigoUsuarioCorresponsal: ").Append(CodigoUsuarioCorresponsal).Append("\n");
            sb.Append("  MensajeTexto: ").Append(MensajeTexto).Append("\n");
            sb.Append("  NumeroCelular: ").Append(NumeroCelular).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EnvioSMSME);
        }

        /// <summary>
        /// Returns true if EnvioSMSME instances are equal
        /// </summary>
        /// <param name="input">Instance of EnvioSMSME to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EnvioSMSME input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SecuencialTipoIdentificacion == input.SecuencialTipoIdentificacion ||
                    this.SecuencialTipoIdentificacion.Equals(input.SecuencialTipoIdentificacion)
                ) && 
                (
                    this.NumeroIdentificacion == input.NumeroIdentificacion ||
                    (this.NumeroIdentificacion != null &&
                    this.NumeroIdentificacion.Equals(input.NumeroIdentificacion))
                ) && 
                (
                    this.CodigoUsuarioCorresponsal == input.CodigoUsuarioCorresponsal ||
                    (this.CodigoUsuarioCorresponsal != null &&
                    this.CodigoUsuarioCorresponsal.Equals(input.CodigoUsuarioCorresponsal))
                ) && 
                (
                    this.MensajeTexto == input.MensajeTexto ||
                    (this.MensajeTexto != null &&
                    this.MensajeTexto.Equals(input.MensajeTexto))
                ) &&
                (
                    this.NumeroCelular == input.NumeroCelular ||
                    (this.NumeroCelular != null &&
                    this.NumeroCelular.Equals(input.NumeroCelular))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.SecuencialTipoIdentificacion.GetHashCode();
                if (this.NumeroIdentificacion != null)
                {
                    hashCode = (hashCode * 59) + this.NumeroIdentificacion.GetHashCode();
                }
                if (this.CodigoUsuarioCorresponsal != null)
                {
                    hashCode = (hashCode * 59) + this.CodigoUsuarioCorresponsal.GetHashCode();
                }
                if (this.MensajeTexto != null)
                {
                    hashCode = (hashCode * 59) + this.MensajeTexto.GetHashCode();
                }
                if (this.NumeroCelular != null)
                {
                    hashCode = (hashCode * 59) + this.NumeroCelular.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
