/*
 * FBSCorresponsalesApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ObtenerProductosMS
    /// </summary>
    [DataContract(Name = "ObtenerProductosMS")]
    public partial class ObtenerProductosMS : IEquatable<ObtenerProductosMS>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ObtenerProductosMS" /> class.
        /// </summary>
        /// <param name="productos">productos.</param>
        public ObtenerProductosMS(List<ProductosMS> productos = default(List<ProductosMS>))
        {
            this.Productos = productos;
        }

        /// <summary>
        /// Gets or Sets Productos
        /// </summary>
        [DataMember(Name = "Productos", EmitDefaultValue = false)]
        public List<ProductosMS> Productos { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ObtenerProductosMS {\n");
            sb.Append("  Productos: ").Append(Productos).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ObtenerProductosMS);
        }

        /// <summary>
        /// Returns true if ObtenerProductosMS instances are equal
        /// </summary>
        /// <param name="input">Instance of ObtenerProductosMS to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ObtenerProductosMS input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Productos == input.Productos ||
                    this.Productos != null &&
                    input.Productos != null &&
                    this.Productos.SequenceEqual(input.Productos)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Productos != null)
                {
                    hashCode = (hashCode * 59) + this.Productos.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
