/*
 * FBSCorresponsalesApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PorIdentificacionSocioME
    /// </summary>
    [DataContract(Name = "PorIdentificacionSocioME")]
    public partial class PorIdentificacionSocioME : IEquatable<PorIdentificacionSocioME>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PorIdentificacionSocioME" /> class.
        /// </summary>
        /// <param name="identificacion">identificacion.</param>
        /// <param name="secuencialTipoIdentificacion">secuencialTipoIdentificacion.</param>
        public PorIdentificacionSocioME(string identificacion = default(string), int secuencialTipoIdentificacion = default(int))
        {
            this.Identificacion = identificacion;
            this.SecuencialTipoIdentificacion = secuencialTipoIdentificacion;
        }

        /// <summary>
        /// Gets or Sets Identificacion
        /// </summary>
        [DataMember(Name = "Identificacion", EmitDefaultValue = false)]
        public string Identificacion { get; set; }

        /// <summary>
        /// Gets or Sets SecuencialTipoIdentificacion
        /// </summary>
        [DataMember(Name = "SecuencialTipoIdentificacion", EmitDefaultValue = false)]
        public int SecuencialTipoIdentificacion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PorIdentificacionSocioME {\n");
            sb.Append("  Identificacion: ").Append(Identificacion).Append("\n");
            sb.Append("  SecuencialTipoIdentificacion: ").Append(SecuencialTipoIdentificacion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PorIdentificacionSocioME);
        }

        /// <summary>
        /// Returns true if PorIdentificacionSocioME instances are equal
        /// </summary>
        /// <param name="input">Instance of PorIdentificacionSocioME to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PorIdentificacionSocioME input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Identificacion == input.Identificacion ||
                    (this.Identificacion != null &&
                    this.Identificacion.Equals(input.Identificacion))
                ) && 
                (
                    this.SecuencialTipoIdentificacion == input.SecuencialTipoIdentificacion ||
                    this.SecuencialTipoIdentificacion.Equals(input.SecuencialTipoIdentificacion)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Identificacion != null)
                {
                    hashCode = (hashCode * 59) + this.Identificacion.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.SecuencialTipoIdentificacion.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
