/*
 * FBSCorresponsalesApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ProductosMS
    /// </summary>
    [DataContract(Name = "ProductosMS")]
    public partial class ProductosMS : IEquatable<ProductosMS>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductosMS" /> class.
        /// </summary>
        /// <param name="idProducto">idProducto.</param>
        /// <param name="nombre">nombre.</param>
        /// <param name="comisionRubro">comisionRubro.</param>
        /// <param name="tipoDatoReferencia">tipoDatoReferencia.</param>
        /// <param name="longitudReferencia">longitudReferencia.</param>
        /// <param name="tipoPago">tipoPago.</param>
        /// <param name="consultaAuxiliar">consultaAuxiliar.</param>
        /// <param name="tipoControl">tipoControl.</param>
        /// <param name="infoAdd">infoAdd.</param>
        /// <param name="urlImagen">urlImagen.</param>
        /// <param name="valoresRecarga">valoresRecarga.</param>
        /// <param name="trxConsulta">trxConsulta.</param>
        public ProductosMS(Guid idProducto = default(Guid), string nombre = default(string), bool comisionRubro = default(bool), string tipoDatoReferencia = default(string), string longitudReferencia = default(string), string tipoPago = default(string), string consultaAuxiliar = default(string), string tipoControl = default(string), string infoAdd = default(string), string urlImagen = default(string), string valoresRecarga = default(string), string trxConsulta = default(string))
        {
            this.IdProducto = idProducto;
            this.Nombre = nombre;
            this.ComisionRubro = comisionRubro;
            this.TipoDatoReferencia = tipoDatoReferencia;
            this.LongitudReferencia = longitudReferencia;
            this.TipoPago = tipoPago;
            this.ConsultaAuxiliar = consultaAuxiliar;
            this.TipoControl = tipoControl;
            this.InfoAdd = infoAdd;
            this.UrlImagen = urlImagen;
            this.ValoresRecarga = valoresRecarga;
            this.TrxConsulta = trxConsulta;
        }

        /// <summary>
        /// Gets or Sets IdProducto
        /// </summary>
        [DataMember(Name = "IdProducto", EmitDefaultValue = false)]
        public Guid IdProducto { get; set; }

        /// <summary>
        /// Gets or Sets Nombre
        /// </summary>
        [DataMember(Name = "Nombre", EmitDefaultValue = false)]
        public string Nombre { get; set; }

        /// <summary>
        /// Gets or Sets ComisionRubro
        /// </summary>
        [DataMember(Name = "ComisionRubro", EmitDefaultValue = true)]
        public bool ComisionRubro { get; set; }

        /// <summary>
        /// Gets or Sets TipoDatoReferencia
        /// </summary>
        [DataMember(Name = "TipoDatoReferencia", EmitDefaultValue = false)]
        public string TipoDatoReferencia { get; set; }

        /// <summary>
        /// Gets or Sets LongitudReferencia
        /// </summary>
        [DataMember(Name = "LongitudReferencia", EmitDefaultValue = false)]
        public string LongitudReferencia { get; set; }

        /// <summary>
        /// Gets or Sets TipoPago
        /// </summary>
        [DataMember(Name = "TipoPago", EmitDefaultValue = false)]
        public string TipoPago { get; set; }

        /// <summary>
        /// Gets or Sets ConsultaAuxiliar
        /// </summary>
        [DataMember(Name = "ConsultaAuxiliar", EmitDefaultValue = false)]
        public string ConsultaAuxiliar { get; set; }

        /// <summary>
        /// Gets or Sets TipoControl
        /// </summary>
        [DataMember(Name = "TipoControl", EmitDefaultValue = false)]
        public string TipoControl { get; set; }

        /// <summary>
        /// Gets or Sets InfoAdd
        /// </summary>
        [DataMember(Name = "InfoAdd", EmitDefaultValue = false)]
        public string InfoAdd { get; set; }

        /// <summary>
        /// Gets or Sets UrlImagen
        /// </summary>
        [DataMember(Name = "UrlImagen", EmitDefaultValue = false)]
        public string UrlImagen { get; set; }

        /// <summary>
        /// Gets or Sets ValoresRecarga
        /// </summary>
        [DataMember(Name = "ValoresRecarga", EmitDefaultValue = false)]
        public string ValoresRecarga { get; set; }

        /// <summary>
        /// Gets or Sets TrxConsulta
        /// </summary>
        [DataMember(Name = "TrxConsulta", EmitDefaultValue = false)]
        public string TrxConsulta { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProductosMS {\n");
            sb.Append("  IdProducto: ").Append(IdProducto).Append("\n");
            sb.Append("  Nombre: ").Append(Nombre).Append("\n");
            sb.Append("  ComisionRubro: ").Append(ComisionRubro).Append("\n");
            sb.Append("  TipoDatoReferencia: ").Append(TipoDatoReferencia).Append("\n");
            sb.Append("  LongitudReferencia: ").Append(LongitudReferencia).Append("\n");
            sb.Append("  TipoPago: ").Append(TipoPago).Append("\n");
            sb.Append("  ConsultaAuxiliar: ").Append(ConsultaAuxiliar).Append("\n");
            sb.Append("  TipoControl: ").Append(TipoControl).Append("\n");
            sb.Append("  InfoAdd: ").Append(InfoAdd).Append("\n");
            sb.Append("  UrlImagen: ").Append(UrlImagen).Append("\n");
            sb.Append("  ValoresRecarga: ").Append(ValoresRecarga).Append("\n");
            sb.Append("  TrxConsulta: ").Append(TrxConsulta).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProductosMS);
        }

        /// <summary>
        /// Returns true if ProductosMS instances are equal
        /// </summary>
        /// <param name="input">Instance of ProductosMS to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductosMS input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.IdProducto == input.IdProducto ||
                    (this.IdProducto != null &&
                    this.IdProducto.Equals(input.IdProducto))
                ) && 
                (
                    this.Nombre == input.Nombre ||
                    (this.Nombre != null &&
                    this.Nombre.Equals(input.Nombre))
                ) && 
                (
                    this.ComisionRubro == input.ComisionRubro ||
                    this.ComisionRubro.Equals(input.ComisionRubro)
                ) && 
                (
                    this.TipoDatoReferencia == input.TipoDatoReferencia ||
                    (this.TipoDatoReferencia != null &&
                    this.TipoDatoReferencia.Equals(input.TipoDatoReferencia))
                ) && 
                (
                    this.LongitudReferencia == input.LongitudReferencia ||
                    (this.LongitudReferencia != null &&
                    this.LongitudReferencia.Equals(input.LongitudReferencia))
                ) && 
                (
                    this.TipoPago == input.TipoPago ||
                    (this.TipoPago != null &&
                    this.TipoPago.Equals(input.TipoPago))
                ) && 
                (
                    this.ConsultaAuxiliar == input.ConsultaAuxiliar ||
                    (this.ConsultaAuxiliar != null &&
                    this.ConsultaAuxiliar.Equals(input.ConsultaAuxiliar))
                ) && 
                (
                    this.TipoControl == input.TipoControl ||
                    (this.TipoControl != null &&
                    this.TipoControl.Equals(input.TipoControl))
                ) && 
                (
                    this.InfoAdd == input.InfoAdd ||
                    (this.InfoAdd != null &&
                    this.InfoAdd.Equals(input.InfoAdd))
                ) && 
                (
                    this.UrlImagen == input.UrlImagen ||
                    (this.UrlImagen != null &&
                    this.UrlImagen.Equals(input.UrlImagen))
                ) && 
                (
                    this.ValoresRecarga == input.ValoresRecarga ||
                    (this.ValoresRecarga != null &&
                    this.ValoresRecarga.Equals(input.ValoresRecarga))
                ) && 
                (
                    this.TrxConsulta == input.TrxConsulta ||
                    (this.TrxConsulta != null &&
                    this.TrxConsulta.Equals(input.TrxConsulta))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IdProducto != null)
                {
                    hashCode = (hashCode * 59) + this.IdProducto.GetHashCode();
                }
                if (this.Nombre != null)
                {
                    hashCode = (hashCode * 59) + this.Nombre.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ComisionRubro.GetHashCode();
                if (this.TipoDatoReferencia != null)
                {
                    hashCode = (hashCode * 59) + this.TipoDatoReferencia.GetHashCode();
                }
                if (this.LongitudReferencia != null)
                {
                    hashCode = (hashCode * 59) + this.LongitudReferencia.GetHashCode();
                }
                if (this.TipoPago != null)
                {
                    hashCode = (hashCode * 59) + this.TipoPago.GetHashCode();
                }
                if (this.ConsultaAuxiliar != null)
                {
                    hashCode = (hashCode * 59) + this.ConsultaAuxiliar.GetHashCode();
                }
                if (this.TipoControl != null)
                {
                    hashCode = (hashCode * 59) + this.TipoControl.GetHashCode();
                }
                if (this.InfoAdd != null)
                {
                    hashCode = (hashCode * 59) + this.InfoAdd.GetHashCode();
                }
                if (this.UrlImagen != null)
                {
                    hashCode = (hashCode * 59) + this.UrlImagen.GetHashCode();
                }
                if (this.ValoresRecarga != null)
                {
                    hashCode = (hashCode * 59) + this.ValoresRecarga.GetHashCode();
                }
                if (this.TrxConsulta != null)
                {
                    hashCode = (hashCode * 59) + this.TrxConsulta.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
