/*
 * FBSCorresponsalesApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// TipoCuentaMS
    /// </summary>
    [DataContract(Name = "TipoCuentaMS")]
    public partial class TipoCuentaMS : IEquatable<TipoCuentaMS>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TipoCuentaMS" /> class.
        /// </summary>
        /// <param name="codigo">codigo.</param>
        /// <param name="nombre">nombre.</param>
        /// <param name="valorApertura">valorApertura.</param>
        public TipoCuentaMS(string codigo = default(string), string nombre = default(string), double valorApertura = default(double))
        {
            this.Codigo = codigo;
            this.Nombre = nombre;
            this.ValorApertura = valorApertura;
        }

        /// <summary>
        /// Gets or Sets Codigo
        /// </summary>
        [DataMember(Name = "Codigo", EmitDefaultValue = false)]
        public string Codigo { get; set; }

        /// <summary>
        /// Gets or Sets Nombre
        /// </summary>
        [DataMember(Name = "Nombre", EmitDefaultValue = false)]
        public string Nombre { get; set; }

        /// <summary>
        /// Gets or Sets ValorApertura
        /// </summary>
        [DataMember(Name = "ValorApertura", EmitDefaultValue = false)]
        public double ValorApertura { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TipoCuentaMS {\n");
            sb.Append("  Codigo: ").Append(Codigo).Append("\n");
            sb.Append("  Nombre: ").Append(Nombre).Append("\n");
            sb.Append("  ValorApertura: ").Append(ValorApertura).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TipoCuentaMS);
        }

        /// <summary>
        /// Returns true if TipoCuentaMS instances are equal
        /// </summary>
        /// <param name="input">Instance of TipoCuentaMS to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TipoCuentaMS input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Codigo == input.Codigo ||
                    (this.Codigo != null &&
                    this.Codigo.Equals(input.Codigo))
                ) && 
                (
                    this.Nombre == input.Nombre ||
                    (this.Nombre != null &&
                    this.Nombre.Equals(input.Nombre))
                ) && 
                (
                    this.ValorApertura == input.ValorApertura ||
                    this.ValorApertura.Equals(input.ValorApertura)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Codigo != null)
                {
                    hashCode = (hashCode * 59) + this.Codigo.GetHashCode();
                }
                if (this.Nombre != null)
                {
                    hashCode = (hashCode * 59) + this.Nombre.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ValorApertura.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
