<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="8.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="6.1.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FBSConsolaCB_WebApi.Domain.Models\FBSConsolaCB_WebApi.Domain.Models.csproj" />
    <ProjectReference Include="..\FBSConsolaCB_WebApi.Infraestructure\FBSConsolaCB_WebApi.Infraestructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="FBS_Core.Base.Domain.Models">
      <HintPath>..\..\..\FBS_Core\FBS_Core.Identity.Domain.Services\bin\Debug\netcoreapp2.2\FBS_Core.Base.Domain.Models.dll</HintPath>
    </Reference>
    <Reference Include="FBS_Core.Base.Domain.Services">
      <HintPath>..\..\..\FBS_Core\FBS_Core.Identity.Domain.Services\bin\Debug\netcoreapp2.2\FBS_Core.Base.Domain.Services.dll</HintPath>
    </Reference>
    <Reference Include="FBS_Core.Base.Infraestructure">
      <HintPath>..\..\..\FBS_Core\FBS_Core.Base.Infraestructure\bin\Debug\netcoreapp2.2\FBS_Core.Base.Infraestructure.dll</HintPath>
    </Reference>
    <Reference Include="FBS_Core.Identity.DAL">
      <HintPath>..\..\..\FBS_Core\FBS_Core.Identity.Domain.Services\bin\Debug\netcoreapp2.2\FBS_Core.Identity.DAL.dll</HintPath>
    </Reference>
    <Reference Include="FBS_Core.Identity.Domain.Models">
      <HintPath>..\..\..\FBS_Core\FBS_Core.Identity.Domain.Services\bin\Debug\netcoreapp2.2\FBS_Core.Identity.Domain.Models.dll</HintPath>
    </Reference>
    <Reference Include="FBS_Core.Identity.Domain.Services">
      <HintPath>..\..\..\FBS_Core\FBS_Core.Identity.Domain.Services\bin\Debug\netcoreapp2.2\FBS_Core.Identity.Domain.Services.dll</HintPath>
    </Reference>
    <Reference Include="FBS_Core.Identity.Infraestructure">
      <HintPath>..\..\..\FBS_Core\FBS_Core.Identity.Domain.Services\bin\Debug\netcoreapp2.2\FBS_Core.Identity.Infraestructure.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
