/*
 * Corresponsales.Query.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Corresponsales.Query.Client.OpenAPIDateConverter;

namespace Corresponsales.Query.Model
{
    /// <summary>
    /// DevuelveNombreEmpresaResponse
    /// </summary>
    [DataContract(Name = "DevuelveNombreEmpresaResponse")]
    public partial class DevuelveNombreEmpresaResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DevuelveNombreEmpresaResponse" /> class.
        /// </summary>
        /// <param name="nombreEmpresa">nombreEmpresa.</param>
        public DevuelveNombreEmpresaResponse(string nombreEmpresa = default(string))
        {
            this.NombreEmpresa = nombreEmpresa;
        }

        /// <summary>
        /// Gets or Sets NombreEmpresa
        /// </summary>
        [DataMember(Name = "nombreEmpresa", EmitDefaultValue = true)]
        public string NombreEmpresa { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DevuelveNombreEmpresaResponse {\n");
            sb.Append("  NombreEmpresa: ").Append(NombreEmpresa).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}

