// <auto-generated>
/*
 * Corresponsales.Query.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Corresponsales.Query.Client;

namespace Corresponsales.Query.Model
{
    /// <summary>
    /// DevuelveCuentasPorCobrarDeUnClienteResponse
    /// </summary>
    public partial class DevuelveCuentasPorCobrarDeUnClienteResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DevuelveCuentasPorCobrarDeUnClienteResponse" /> class.
        /// </summary>
        /// <param name="datosClienteRubrosPorCobrar">datosClienteRubrosPorCobrar</param>
        [JsonConstructor]
        public DevuelveCuentasPorCobrarDeUnClienteResponse(List<DatosClienteRubrosPorCobrarResponse>? datosClienteRubrosPorCobrar = default)
        {
            DatosClienteRubrosPorCobrarOption = datosClienteRubrosPorCobrar;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of DatosClienteRubrosPorCobrar
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public List<DatosClienteRubrosPorCobrarResponse>? DatosClienteRubrosPorCobrarOption { get; private set; }

        /// <summary>
        /// Gets or Sets DatosClienteRubrosPorCobrar
        /// </summary>
        [JsonPropertyName("datosClienteRubrosPorCobrar")]
        public List<DatosClienteRubrosPorCobrarResponse>? DatosClienteRubrosPorCobrar { get { return this.DatosClienteRubrosPorCobrarOption; } set { this.DatosClienteRubrosPorCobrarOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DevuelveCuentasPorCobrarDeUnClienteResponse {\n");
            sb.Append("  DatosClienteRubrosPorCobrar: ").Append(DatosClienteRubrosPorCobrar).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }   
}
