/*
 * Corresponsales.Command.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace Corresponsales.Query.Model
{
    /// <summary>
    /// ServicioDto
    /// </summary>
    [DataContract(Name = "ServicioDto")]
    public partial class ServicioDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServicioDto" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="business">business.</param>
        /// <param name="nombre">nombre.</param>
        /// <param name="descripcion">descripcion.</param>
        /// <param name="tipoServicio">tipoServicio.</param>
        public ServicioDto(string id = default(string), string business = default(string), string nombre = default(string), string descripcion = default(string), ServicioTipoDto tipoServicio = default(ServicioTipoDto))
        {
            this.Id = id;
            this.Business = business;
            this.Nombre = nombre;
            this.Descripcion = descripcion;
            this.TipoServicio = tipoServicio;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Business
        /// </summary>
        [DataMember(Name = "business", EmitDefaultValue = true)]
        public string Business { get; set; }

        /// <summary>
        /// Gets or Sets Nombre
        /// </summary>
        [DataMember(Name = "nombre", EmitDefaultValue = true)]
        public string Nombre { get; set; }

        /// <summary>
        /// Gets or Sets Descripcion
        /// </summary>
        [DataMember(Name = "descripcion", EmitDefaultValue = true)]
        public string Descripcion { get; set; }

        /// <summary>
        /// Gets or Sets TipoServicio
        /// </summary>
        [DataMember(Name = "tipoServicio", EmitDefaultValue = false)]
        public ServicioTipoDto TipoServicio { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ServicioDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Business: ").Append(Business).Append("\n");
            sb.Append("  Nombre: ").Append(Nombre).Append("\n");
            sb.Append("  Descripcion: ").Append(Descripcion).Append("\n");
            sb.Append("  TipoServicio: ").Append(TipoServicio).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}