<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="8.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="6.1.1" />
    <PackageReference Include="MailKit" Version="2.2.0" />
    <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.20" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FBSConsolaCB_WebApi.Dominio.Modelos\FBSConsolaCB_WebApi.Dominio.Modelos.csproj" />
    <ProjectReference Include="..\FBSConsolaCB_WebApi.Infraestructura\FBSConsolaCB_WebApi.Infraestructura.csproj" />
    <ProjectReference Include="..\FBS_Core\FBS.Identidad.Dominio.Servicios\FBS.Identidad.Dominio.Servicios.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="FBS_Financial_Services_Banca">
      <HintPath>..\FBSConsolaCB_WebApi.WebApi\Resources\dll\FBS_Financial_Services_Banca.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
