// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AfectacionMS
    {
        /// <summary>
        /// Initializes a new instance of the AfectacionMS class.
        /// </summary>
        public AfectacionMS()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AfectacionMS class.
        /// </summary>
        public AfectacionMS(string codigoTrxEmpresa = default(string), string serialTransaccion = default(string), string codigoTransaccion = default(string), string tipo = default(string), string codigoRespuesta = default(string), string fechaTransaccion = default(string), string mensajeRespuesta = default(string), double? montoPago = default(double?), double? montoComision = default(double?), double? montoTotal = default(double?), int? secuencialResultadoPago = default(int?), double? saldoCuentaCorresponsal = default(double?), string documento = default(string), ImpresionMS impresion = default(ImpresionMS))
        {
            CodigoTrxEmpresa = codigoTrxEmpresa;
            SerialTransaccion = serialTransaccion;
            CodigoTransaccion = codigoTransaccion;
            Tipo = tipo;
            CodigoRespuesta = codigoRespuesta;
            FechaTransaccion = fechaTransaccion;
            MensajeRespuesta = mensajeRespuesta;
            MontoPago = montoPago;
            MontoComision = montoComision;
            MontoTotal = montoTotal;
            SecuencialResultadoPago = secuencialResultadoPago;
            SaldoCuentaCorresponsal = saldoCuentaCorresponsal;
            Documento = documento;
            Impresion = impresion;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Codigo_trx_empresa")]
        public string CodigoTrxEmpresa { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Serial_transaccion")]
        public string SerialTransaccion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Codigo_transaccion")]
        public string CodigoTransaccion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Tipo")]
        public string Tipo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Codigo_respuesta")]
        public string CodigoRespuesta { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Fecha_transaccion")]
        public string FechaTransaccion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Mensaje_respuesta")]
        public string MensajeRespuesta { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Monto_pago")]
        public double? MontoPago { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Monto_comision")]
        public double? MontoComision { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Monto_total")]
        public double? MontoTotal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SecuencialResultadoPago")]
        public int? SecuencialResultadoPago { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SaldoCuentaCorresponsal")]
        public double? SaldoCuentaCorresponsal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Documento")]
        public string Documento { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Impresion")]
        public ImpresionMS Impresion { get; set; }

    }
}
