// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CampoPagoMS
    {
        /// <summary>
        /// Initializes a new instance of the CampoPagoMS class.
        /// </summary>
        public CampoPagoMS()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CampoPagoMS class.
        /// </summary>
        public CampoPagoMS(int? id = default(int?), string etiqueta = default(string), string nombre = default(string), string abono = default(string), string tipo = default(string), IList<CatalogoPagoMS> catalogos = default(IList<CatalogoPagoMS>))
        {
            Id = id;
            Etiqueta = etiqueta;
            Nombre = nombre;
            Abono = abono;
            Tipo = tipo;
            Catalogos = catalogos;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Etiqueta")]
        public string Etiqueta { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Nombre")]
        public string Nombre { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Abono")]
        public string Abono { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Tipo")]
        public string Tipo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Catalogos")]
        public IList<CatalogoPagoMS> Catalogos { get; set; }

    }
}
