// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClientePersonalizadoInformacion
    {
        /// <summary>
        /// Initializes a new instance of the ClientePersonalizadoInformacion
        /// class.
        /// </summary>
        public ClientePersonalizadoInformacion()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClientePersonalizadoInformacion
        /// class.
        /// </summary>
        public ClientePersonalizadoInformacion(int? secuencial = default(int?), string identificacionBeneficiarioSeguroVida = default(string), string beneficiarioSeguroDeVida = default(string), string parentesco = default(string), string direccion = default(string), string telefono = default(string), double? porcentaje = default(double?))
        {
            Secuencial = secuencial;
            IdentificacionBeneficiarioSeguroVida = identificacionBeneficiarioSeguroVida;
            BeneficiarioSeguroDeVida = beneficiarioSeguroDeVida;
            Parentesco = parentesco;
            Direccion = direccion;
            Telefono = telefono;
            Porcentaje = porcentaje;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Secuencial")]
        public int? Secuencial { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IdentificacionBeneficiarioSeguroVida")]
        public string IdentificacionBeneficiarioSeguroVida { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BeneficiarioSeguroDeVida")]
        public string BeneficiarioSeguroDeVida { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Parentesco")]
        public string Parentesco { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Direccion")]
        public string Direccion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Telefono")]
        public string Telefono { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Porcentaje")]
        public double? Porcentaje { get; set; }

    }
}
