// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ConsolidadoCuentasMSL
    {
        /// <summary>
        /// Initializes a new instance of the ConsolidadoCuentasMSL class.
        /// </summary>
        public ConsolidadoCuentasMSL()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConsolidadoCuentasMSL class.
        /// </summary>
        public ConsolidadoCuentasMSL(IList<CuentaDetalleConsolidadoMS> cuentaDetallesConsolidado = default(IList<CuentaDetalleConsolidadoMS>))
        {
            CuentaDetallesConsolidado = cuentaDetallesConsolidado;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CuentaDetallesConsolidado")]
        public IList<CuentaDetalleConsolidadoMS> CuentaDetallesConsolidado { get; set; }

    }
}
