// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CreaCuentaMSL
    {
        /// <summary>
        /// Initializes a new instance of the CreaCuentaMSL class.
        /// </summary>
        public CreaCuentaMSL()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreaCuentaMSL class.
        /// </summary>
        public CreaCuentaMSL(IList<CuentaMS> cuentasCreadas = default(IList<CuentaMS>))
        {
            CuentasCreadas = cuentasCreadas;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CuentasCreadas")]
        public IList<CuentaMS> CuentasCreadas { get; set; }

    }
}
