// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreaCuentaME
    {
        /// <summary>
        /// Initializes a new instance of the CreaCuentaME class.
        /// </summary>
        public CreaCuentaME()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreaCuentaME class.
        /// </summary>
        public CreaCuentaME(string codigoTipoCuenta = default(string), int? secuencialCliente = default(int?))
        {
            CodigoTipoCuenta = codigoTipoCuenta;
            SecuencialCliente = secuencialCliente;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CodigoTipoCuenta")]
        public string CodigoTipoCuenta { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SecuencialCliente")]
        public int? SecuencialCliente { get; set; }

    }
}
