// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DevuelveCuentaME
    {
        /// <summary>
        /// Initializes a new instance of the DevuelveCuentaME class.
        /// </summary>
        public DevuelveCuentaME()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DevuelveCuentaME class.
        /// </summary>
        public DevuelveCuentaME(int? secuencialCuenta = default(int?))
        {
            SecuencialCuenta = secuencialCuenta;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SecuencialCuenta")]
        public int? SecuencialCuenta { get; set; }

    }
}
