// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EfectivizacionPrestamoMS
    {
        /// <summary>
        /// Initializes a new instance of the EfectivizacionPrestamoMS class.
        /// </summary>
        public EfectivizacionPrestamoMS()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EfectivizacionPrestamoMS class.
        /// </summary>
        public EfectivizacionPrestamoMS(string numeroPrestamo = default(string), string numeroDocumento = default(string), string fecha = default(string), double? valor = default(double?), double? saldoPrestamo = default(double?), double? saldoCuentaCorresponsal = default(double?))
        {
            NumeroPrestamo = numeroPrestamo;
            NumeroDocumento = numeroDocumento;
            Fecha = fecha;
            Valor = valor;
            SaldoPrestamo = saldoPrestamo;
            SaldoCuentaCorresponsal = saldoCuentaCorresponsal;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumeroPrestamo")]
        public string NumeroPrestamo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumeroDocumento")]
        public string NumeroDocumento { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Fecha")]
        public string Fecha { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Valor")]
        public double? Valor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SaldoPrestamo")]
        public double? SaldoPrestamo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SaldoCuentaCorresponsal")]
        public double? SaldoCuentaCorresponsal { get; set; }

    }
}
