// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FacilitoPagoMS
    {
        /// <summary>
        /// Initializes a new instance of the FacilitoPagoMS class.
        /// </summary>
        public FacilitoPagoMS()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FacilitoPagoMS class.
        /// </summary>
        public FacilitoPagoMS(double? saldoCuentaCorresponsal = default(double?), double? saldoCuentaCliente = default(double?), System.DateTime? fechaTransaccion = default(System.DateTime?), string jsonRespuestaFacilito = default(string))
        {
            SaldoCuentaCorresponsal = saldoCuentaCorresponsal;
            SaldoCuentaCliente = saldoCuentaCliente;
            FechaTransaccion = fechaTransaccion;
            JsonRespuestaFacilito = jsonRespuestaFacilito;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SaldoCuentaCorresponsal")]
        public double? SaldoCuentaCorresponsal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SaldoCuentaCliente")]
        public double? SaldoCuentaCliente { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FechaTransaccion")]
        public System.DateTime? FechaTransaccion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "JsonRespuestaFacilito")]
        public string JsonRespuestaFacilito { get; set; }

    }
}
