// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ImpresionMS
    {
        /// <summary>
        /// Initializes a new instance of the ImpresionMS class.
        /// </summary>
        public ImpresionMS()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ImpresionMS class.
        /// </summary>
        public ImpresionMS(IList<ReciboMS> recibos = default(IList<ReciboMS>))
        {
            Recibos = recibos;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recibos")]
        public IList<ReciboMS> Recibos { get; set; }

    }
}
