// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NuevaPersonaNaturalMinimoClienteME
    {
        /// <summary>
        /// Initializes a new instance of the
        /// NuevaPersonaNaturalMinimoClienteME class.
        /// </summary>
        public NuevaPersonaNaturalMinimoClienteME()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// NuevaPersonaNaturalMinimoClienteME class.
        /// </summary>
        public NuevaPersonaNaturalMinimoClienteME(int? secuencialOficinaGraba = default(int?), bool? seHaraCliente = default(bool?), string identificacion = default(string), string direccionDomicilio = default(string), int? secuencialTipoIdentificacion = default(int?), int? secuencialDivisionActividadEconomica = default(int?), string apellidoPaterno = default(string), string apellidoMaterno = default(string), string nombres = default(string), System.DateTime? fechaNacimiento = default(System.DateTime?), bool? esMasculino = default(bool?), string numeroPapeletaVotacion = default(string), int? cargasFamiliares = default(int?), string codigoEstadoCivil = default(string), string codigoTipoVivienda = default(string), double? activosTotales = default(double?), double? pasivosTotales = default(double?), double? patrimonio = default(double?), string telefonoDomicilio = default(string), bool? visualizaMensajeDeExistencia = default(bool?), int? secuencialDivisionPoliticaResidencia = default(int?), string codigoTelefono = default(string), int? numeroMesesArriendo = default(int?), int? secuencialDivisionPoliticaNacimiento = default(int?), bool? esObligadoLLevarContabilidad = default(bool?), double? ventasAnuales = default(double?))
        {
            SecuencialOficinaGraba = secuencialOficinaGraba;
            SeHaraCliente = seHaraCliente;
            Identificacion = identificacion;
            DireccionDomicilio = direccionDomicilio;
            SecuencialTipoIdentificacion = secuencialTipoIdentificacion;
            SecuencialDivisionActividadEconomica = secuencialDivisionActividadEconomica;
            ApellidoPaterno = apellidoPaterno;
            ApellidoMaterno = apellidoMaterno;
            Nombres = nombres;
            FechaNacimiento = fechaNacimiento;
            EsMasculino = esMasculino;
            NumeroPapeletaVotacion = numeroPapeletaVotacion;
            CargasFamiliares = cargasFamiliares;
            CodigoEstadoCivil = codigoEstadoCivil;
            CodigoTipoVivienda = codigoTipoVivienda;
            ActivosTotales = activosTotales;
            PasivosTotales = pasivosTotales;
            Patrimonio = patrimonio;
            TelefonoDomicilio = telefonoDomicilio;
            VisualizaMensajeDeExistencia = visualizaMensajeDeExistencia;
            SecuencialDivisionPoliticaResidencia = secuencialDivisionPoliticaResidencia;
            CodigoTelefono = codigoTelefono;
            NumeroMesesArriendo = numeroMesesArriendo;
            SecuencialDivisionPoliticaNacimiento = secuencialDivisionPoliticaNacimiento;
            EsObligadoLLevarContabilidad = esObligadoLLevarContabilidad;
            VentasAnuales = ventasAnuales;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SecuencialOficinaGraba")]
        public int? SecuencialOficinaGraba { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SeHaraCliente")]
        public bool? SeHaraCliente { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Identificacion")]
        public string Identificacion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DireccionDomicilio")]
        public string DireccionDomicilio { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SecuencialTipoIdentificacion")]
        public int? SecuencialTipoIdentificacion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SecuencialDivisionActividadEconomica")]
        public int? SecuencialDivisionActividadEconomica { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ApellidoPaterno")]
        public string ApellidoPaterno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ApellidoMaterno")]
        public string ApellidoMaterno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Nombres")]
        public string Nombres { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FechaNacimiento")]
        public System.DateTime? FechaNacimiento { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EsMasculino")]
        public bool? EsMasculino { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumeroPapeletaVotacion")]
        public string NumeroPapeletaVotacion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CargasFamiliares")]
        public int? CargasFamiliares { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CodigoEstadoCivil")]
        public string CodigoEstadoCivil { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CodigoTipoVivienda")]
        public string CodigoTipoVivienda { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ActivosTotales")]
        public double? ActivosTotales { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PasivosTotales")]
        public double? PasivosTotales { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Patrimonio")]
        public double? Patrimonio { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TelefonoDomicilio")]
        public string TelefonoDomicilio { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VisualizaMensajeDeExistencia")]
        public bool? VisualizaMensajeDeExistencia { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SecuencialDivisionPoliticaResidencia")]
        public int? SecuencialDivisionPoliticaResidencia { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CodigoTelefono")]
        public string CodigoTelefono { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumeroMesesArriendo")]
        public int? NumeroMesesArriendo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SecuencialDivisionPoliticaNacimiento")]
        public int? SecuencialDivisionPoliticaNacimiento { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EsObligadoLLevarContabilidad")]
        public bool? EsObligadoLLevarContabilidad { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VentasAnuales")]
        public double? VentasAnuales { get; set; }

    }
}
