// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ObtenerProductosME
    {
        /// <summary>
        /// Initializes a new instance of the ObtenerProductosME class.
        /// </summary>
        public ObtenerProductosME()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ObtenerProductosME class.
        /// </summary>
        public ObtenerProductosME(System.Guid? idGrupo = default(System.Guid?), string servicio = default(string))
        {
            IdGrupo = idGrupo;
            Servicio = servicio;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IdGrupo")]
        public System.Guid? IdGrupo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Servicio")]
        public string Servicio { get; set; }

    }
}
