// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PagoFacilitoME
    {
        /// <summary>
        /// Initializes a new instance of the PagoFacilitoME class.
        /// </summary>
        public PagoFacilitoME()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PagoFacilitoME class.
        /// </summary>
        public PagoFacilitoME(int? secuencialCuentaCorresponsal = default(int?), int? secuencialCuentaCliente = default(int?), string jsonPagoFacilito = default(string), string jsonComision = default(string), double? valor = default(double?), string codigoUsuario = default(string))
        {
            SecuencialCuentaCorresponsal = secuencialCuentaCorresponsal;
            SecuencialCuentaCliente = secuencialCuentaCliente;
            JsonPagoFacilito = jsonPagoFacilito;
            JsonComision = jsonComision;
            Valor = valor;
            CodigoUsuario = codigoUsuario;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SecuencialCuentaCorresponsal")]
        public int? SecuencialCuentaCorresponsal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SecuencialCuentaCliente")]
        public int? SecuencialCuentaCliente { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "JsonPagoFacilito")]
        public string JsonPagoFacilito { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "JsonComision")]
        public string JsonComision { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Valor")]
        public double? Valor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CodigoUsuario")]
        public string CodigoUsuario { get; set; }

    }
}
