// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PagoFacilitoMSL
    {
        /// <summary>
        /// Initializes a new instance of the PagoFacilitoMSL class.
        /// </summary>
        public PagoFacilitoMSL()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PagoFacilitoMSL class.
        /// </summary>
        public PagoFacilitoMSL(IList<PagoFacilitoMS> pagosFacilito = default(IList<PagoFacilitoMS>), double? saldoCuentaCorresponsal = default(double?))
        {
            PagosFacilito = pagosFacilito;
            SaldoCuentaCorresponsal = saldoCuentaCorresponsal;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PagosFacilito")]
        public IList<PagoFacilitoMS> PagosFacilito { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SaldoCuentaCorresponsal")]
        public double? SaldoCuentaCorresponsal { get; set; }

    }
}
