// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProductosMS
    {
        /// <summary>
        /// Initializes a new instance of the ProductosMS class.
        /// </summary>
        public ProductosMS()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProductosMS class.
        /// </summary>
        public ProductosMS(System.Guid? idProducto = default(System.Guid?), string nombre = default(string), bool? comisionRubro = default(bool?), string tipoDatoReferencia = default(string), string longitudReferencia = default(string), string tipoPago = default(string), string consultaAuxiliar = default(string), string tipoControl = default(string), string infoAdd = default(string), string urlImagen = default(string), string valoresRecarga = default(string), string trxConsulta = default(string))
        {
            IdProducto = idProducto;
            Nombre = nombre;
            ComisionRubro = comisionRubro;
            TipoDatoReferencia = tipoDatoReferencia;
            LongitudReferencia = longitudReferencia;
            TipoPago = tipoPago;
            ConsultaAuxiliar = consultaAuxiliar;
            TipoControl = tipoControl;
            InfoAdd = infoAdd;
            UrlImagen = urlImagen;
            ValoresRecarga = valoresRecarga;
            TrxConsulta = trxConsulta;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IdProducto")]
        public System.Guid? IdProducto { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Nombre")]
        public string Nombre { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ComisionRubro")]
        public bool? ComisionRubro { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TipoDatoReferencia")]
        public string TipoDatoReferencia { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LongitudReferencia")]
        public string LongitudReferencia { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TipoPago")]
        public string TipoPago { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ConsultaAuxiliar")]
        public string ConsultaAuxiliar { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TipoControl")]
        public string TipoControl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InfoAdd")]
        public string InfoAdd { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UrlImagen")]
        public string UrlImagen { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ValoresRecarga")]
        public string ValoresRecarga { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TrxConsulta")]
        public string TrxConsulta { get; set; }

    }
}
