// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ReferenciaComercialInformacion
    {
        /// <summary>
        /// Initializes a new instance of the ReferenciaComercialInformacion
        /// class.
        /// </summary>
        public ReferenciaComercialInformacion()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ReferenciaComercialInformacion
        /// class.
        /// </summary>
        public ReferenciaComercialInformacion(int? secuencial = default(int?), string nombres = default(string), string telefono = default(string), string direccion = default(string), bool? esPersonal = default(bool?))
        {
            Secuencial = secuencial;
            Nombres = nombres;
            Telefono = telefono;
            Direccion = direccion;
            EsPersonal = esPersonal;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Secuencial")]
        public int? Secuencial { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Nombres")]
        public string Nombres { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Telefono")]
        public string Telefono { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Direccion")]
        public string Direccion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EsPersonal")]
        public bool? EsPersonal { get; set; }

    }
}
