// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TelefonoInformacion
    {
        /// <summary>
        /// Initializes a new instance of the TelefonoInformacion class.
        /// </summary>
        public TelefonoInformacion()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TelefonoInformacion class.
        /// </summary>
        public TelefonoInformacion(int? secuencial = default(int?), string empresaTelefonica = default(string), string tipoTelefono = default(string), string numeroTelefono = default(string), string descripcion = default(string), bool? recibeNotificacion = default(bool?))
        {
            Secuencial = secuencial;
            EmpresaTelefonica = empresaTelefonica;
            TipoTelefono = tipoTelefono;
            NumeroTelefono = numeroTelefono;
            Descripcion = descripcion;
            RecibeNotificacion = recibeNotificacion;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Secuencial")]
        public int? Secuencial { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EmpresaTelefonica")]
        public string EmpresaTelefonica { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TipoTelefono")]
        public string TipoTelefono { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumeroTelefono")]
        public string NumeroTelefono { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Descripcion")]
        public string Descripcion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RecibeNotificacion")]
        public bool? RecibeNotificacion { get; set; }

    }
}
