// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TiposCuentaClienteMSL
    {
        /// <summary>
        /// Initializes a new instance of the TiposCuentaClienteMSL class.
        /// </summary>
        public TiposCuentaClienteMSL()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TiposCuentaClienteMSL class.
        /// </summary>
        public TiposCuentaClienteMSL(IList<TipoCuentaMS> tiposCuenta = default(IList<TipoCuentaMS>))
        {
            TiposCuenta = tiposCuenta;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TiposCuenta")]
        public IList<TipoCuentaMS> TiposCuenta { get; set; }

    }
}
