// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ServiciosFinancial.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TiposIdentificacionMSL
    {
        /// <summary>
        /// Initializes a new instance of the TiposIdentificacionMSL class.
        /// </summary>
        public TiposIdentificacionMSL()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TiposIdentificacionMSL class.
        /// </summary>
        public TiposIdentificacionMSL(IList<TipoIdentificacionMS> tiposIdentificacion = default(IList<TipoIdentificacionMS>))
        {
            TiposIdentificacion = tiposIdentificacion;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TiposIdentificacion")]
        public IList<TipoIdentificacionMS> TiposIdentificacion { get; set; }

    }
}
