/*
 * Corresponsales.Command.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Corresponsales.Command.Client.OpenAPIDateConverter;

namespace Corresponsales.Command.Model
{
    /// <summary>
    /// AfectacionCorresponsalRequest
    /// </summary>
    [DataContract(Name = "AfectacionCorresponsalRequest")]
    public partial class AfectacionCorresponsalRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AfectacionCorresponsalRequest" /> class.
        /// </summary>
        /// <param name="tipoTransaccion">tipoTransaccion.</param>
        /// <param name="secuencialCuentaSocio">secuencialCuentaSocio.</param>
        /// <param name="secuencialCuentaCorresponsal">secuencialCuentaCorresponsal.</param>
        /// <param name="valorAfectado">valorAfectado.</param>
        /// <param name="jsonComision">jsonComision.</param>
        /// <param name="codigoUsuario">codigoUsuario.</param>
        /// <param name="esUnSoloCobroComision">esUnSoloCobroComision.</param>
        /// <param name="secuencialTipoIdentificacionCliente">secuencialTipoIdentificacionCliente.</param>
        /// <param name="identificacionCliente">identificacionCliente.</param>
        public AfectacionCorresponsalRequest(string tipoTransaccion = default(string), int secuencialCuentaSocio = default(int), int secuencialCuentaCorresponsal = default(int), double valorAfectado = default(double), string jsonComision = default(string), string codigoUsuario = default(string), bool esUnSoloCobroComision = default(bool), int secuencialTipoIdentificacionCliente = default(int), string identificacionCliente = default(string))
        {
            this.TipoTransaccion = tipoTransaccion;
            this.SecuencialCuentaSocio = secuencialCuentaSocio;
            this.SecuencialCuentaCorresponsal = secuencialCuentaCorresponsal;
            this.ValorAfectado = valorAfectado;
            this.JsonComision = jsonComision;
            this.CodigoUsuario = codigoUsuario;
            this.EsUnSoloCobroComision = esUnSoloCobroComision;
            this.SecuencialTipoIdentificacionCliente = secuencialTipoIdentificacionCliente;
            this.IdentificacionCliente = identificacionCliente;
        }

        /// <summary>
        /// Gets or Sets TipoTransaccion
        /// </summary>
        [DataMember(Name = "tipoTransaccion", EmitDefaultValue = true)]
        public string TipoTransaccion { get; set; }

        /// <summary>
        /// Gets or Sets SecuencialCuentaSocio
        /// </summary>
        [DataMember(Name = "secuencialCuentaSocio", EmitDefaultValue = false)]
        public int SecuencialCuentaSocio { get; set; }

        /// <summary>
        /// Gets or Sets SecuencialCuentaCorresponsal
        /// </summary>
        [DataMember(Name = "secuencialCuentaCorresponsal", EmitDefaultValue = false)]
        public int SecuencialCuentaCorresponsal { get; set; }

        /// <summary>
        /// Gets or Sets ValorAfectado
        /// </summary>
        [DataMember(Name = "valorAfectado", EmitDefaultValue = false)]
        public double ValorAfectado { get; set; }

        /// <summary>
        /// Gets or Sets JsonComision
        /// </summary>
        [DataMember(Name = "jsonComision", EmitDefaultValue = true)]
        public string JsonComision { get; set; }

        /// <summary>
        /// Gets or Sets CodigoUsuario
        /// </summary>
        [DataMember(Name = "codigoUsuario", EmitDefaultValue = true)]
        public string CodigoUsuario { get; set; }

        /// <summary>
        /// Gets or Sets EsUnSoloCobroComision
        /// </summary>
        [DataMember(Name = "esUnSoloCobroComision", EmitDefaultValue = true)]
        public bool EsUnSoloCobroComision { get; set; }

        /// <summary>
        /// Gets or Sets SecuencialTipoIdentificacionCliente
        /// </summary>
        [DataMember(Name = "secuencialTipoIdentificacionCliente", EmitDefaultValue = false)]
        public int SecuencialTipoIdentificacionCliente { get; set; }

        /// <summary>
        /// Gets or Sets IdentificacionCliente
        /// </summary>
        [DataMember(Name = "identificacionCliente", EmitDefaultValue = true)]
        public string IdentificacionCliente { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AfectacionCorresponsalRequest {\n");
            sb.Append("  TipoTransaccion: ").Append(TipoTransaccion).Append("\n");
            sb.Append("  SecuencialCuentaSocio: ").Append(SecuencialCuentaSocio).Append("\n");
            sb.Append("  SecuencialCuentaCorresponsal: ").Append(SecuencialCuentaCorresponsal).Append("\n");
            sb.Append("  ValorAfectado: ").Append(ValorAfectado).Append("\n");
            sb.Append("  JsonComision: ").Append(JsonComision).Append("\n");
            sb.Append("  CodigoUsuario: ").Append(CodigoUsuario).Append("\n");
            sb.Append("  EsUnSoloCobroComision: ").Append(EsUnSoloCobroComision).Append("\n");
            sb.Append("  SecuencialTipoIdentificacionCliente: ").Append(SecuencialTipoIdentificacionCliente).Append("\n");
            sb.Append("  IdentificacionCliente: ").Append(IdentificacionCliente).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
