/*
 * Corresponsales.Command.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Corresponsales.Command.Client.OpenAPIDateConverter;

namespace Corresponsales.Command.Model
{
    /// <summary>
    /// CampoAdicionalRespuesta
    /// </summary>
    [DataContract(Name = "CampoAdicionalRespuesta")]
    public partial class CampoAdicionalRespuesta : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CampoAdicionalRespuesta" /> class.
        /// </summary>
        /// <param name="valor">valor.</param>
        /// <param name="campo">campo.</param>
        public CampoAdicionalRespuesta(string valor = default(string), DetalleCampoAdicional campo = default(DetalleCampoAdicional))
        {
            this.Valor = valor;
            this.Campo = campo;
        }

        /// <summary>
        /// Gets or Sets Valor
        /// </summary>
        [DataMember(Name = "valor", EmitDefaultValue = true)]
        public string Valor { get; set; }

        /// <summary>
        /// Gets or Sets Campo
        /// </summary>
        [DataMember(Name = "campo", EmitDefaultValue = false)]
        public DetalleCampoAdicional Campo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CampoAdicionalRespuesta {\n");
            sb.Append("  Valor: ").Append(Valor).Append("\n");
            sb.Append("  Campo: ").Append(Campo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}