/*
 * Corresponsales.Command.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Corresponsales.Command.Client.OpenAPIDateConverter;

namespace Corresponsales.Command.Model
{
    /// <summary>
    /// CreaUsuarioResponse
    /// </summary>
    [DataContract(Name = "CreaUsuarioResponse")]
    public partial class CreaUsuarioResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreaUsuarioResponse" /> class.
        /// </summary>
        /// <param name="usuarioCreado">usuarioCreado.</param>
        /// <param name="existeUsuario">existeUsuaio.</param>
        
        public CreaUsuarioResponse(
            bool usuarioCreado = default(bool),
            bool existeUsuario = default(bool))
        {
            this.UsuarioCreado = usuarioCreado;
            this.ExisteUsuario = existeUsuario;            
        }

        /// <summary>
        /// Gets or Sets usuarioCreado
        /// </summary>
        [DataMember(Name = "usuarioCreado", EmitDefaultValue = true)]
        public bool UsuarioCreado { get; set; }

        /// <summary>
        /// Gets or Sets existeUsuaio
        /// </summary>
        [DataMember(Name = "existeUsuario", EmitDefaultValue = true)]
        public bool ExisteUsuario { get; set; }        

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreaUsuarioResponse {\n");
            sb.Append("  usuarioCreado: ").Append(UsuarioCreado).Append("\n");
            sb.Append("  existeUsuaio: ").Append(ExisteUsuario).Append("\n");           
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
