/*
 * Corresponsales.Command.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Corresponsales.Command.Client.OpenAPIDateConverter;

namespace Corresponsales.Command.Model
{
    /// <summary>
    /// DetalleComision
    /// </summary>
    [DataContract(Name = "DetalleComision")]
    public partial class DetalleComision : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DetalleComision" /> class.
        /// </summary>
        /// <param name="tipo">tipo.</param>
        /// <param name="monto">monto.</param>
        public DetalleComision(TipoComision tipo = default(TipoComision), Monto monto = default(Monto))
        {
            this.Tipo = tipo;
            this.Monto = monto;
        }

        /// <summary>
        /// Gets or Sets Tipo
        /// </summary>
        [DataMember(Name = "tipo", EmitDefaultValue = false)]
        public TipoComision Tipo { get; set; }

        /// <summary>
        /// Gets or Sets Monto
        /// </summary>
        [DataMember(Name = "monto", EmitDefaultValue = false)]
        public Monto Monto { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DetalleComision {\n");
            sb.Append("  Tipo: ").Append(Tipo).Append("\n");
            sb.Append("  Monto: ").Append(Monto).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}