/*
 * Corresponsales.Command.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Corresponsales.Command.Client.OpenAPIDateConverter;

namespace Corresponsales.Command.Model
{
    /// <summary>
    /// Monto
    /// </summary>
    [DataContract(Name = "Monto")]
    public partial class Monto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Monto" /> class.
        /// </summary>
        /// <param name="cantidad">cantidad.</param>
        /// <param name="moneda">moneda.</param>
        public Monto(double cantidad = default(double), string moneda = default(string))
        {
            this.Cantidad = cantidad;
            this.Moneda = moneda;
        }

        /// <summary>
        /// Gets or Sets Cantidad
        /// </summary>
        [DataMember(Name = "cantidad", EmitDefaultValue = false)]
        public double Cantidad { get; set; }

        /// <summary>
        /// Gets or Sets Moneda
        /// </summary>
        [DataMember(Name = "moneda", EmitDefaultValue = true)]
        public string Moneda { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Monto {\n");
            sb.Append("  Cantidad: ").Append(Cantidad).Append("\n");
            sb.Append("  Moneda: ").Append(Moneda).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}