/*
 * Corresponsales.Command.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Corresponsales.Command.Client.OpenAPIDateConverter;

namespace Corresponsales.Command.Model
{
    /// <summary>
    /// PagoFacilitoMS
    /// </summary>
    [DataContract(Name = "PagoFacilitoMS")]
    public partial class PagoFacilitoMS : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PagoFacilitoMS" /> class.
        /// </summary>
        /// <param name="fechaTransaccion">fechaTransaccion.</param>
        /// <param name="documento">documento.</param>
        /// <param name="codigoResultado">codigoResultado.</param>
        /// <param name="fechaTransaccionFinancial">fechaTransaccionFinancial.</param>
        /// <param name="horaTransaccion">horaTransaccion.</param>
        /// <param name="mensaje">mensaje.</param>
        /// <param name="valorPagado">valorPagado.</param>
        /// <param name="secuencialRespuestaPago">secuencialRespuestaPago.</param>
        /// <param name="secuencialEnvioPago">secuencialEnvioPago.</param>
        /// <param name="operadoPor">operadoPor.</param>
        /// <param name="url">url.</param>
        /// <param name="factura">factura.</param>
        /// <param name="informacionGenerica">informacionGenerica.</param>
        /// <param name="setLog">setLog.</param>
        /// <param name="idCliente">idCliente.</param>
        /// <param name="nombreCliente">nombreCliente.</param>
        public PagoFacilitoMS(string fechaTransaccion = default(string), string documento = default(string), string codigoResultado = default(string), string fechaTransaccionFinancial = default(string), string horaTransaccion = default(string), string mensaje = default(string), double valorPagado = default(double), int secuencialRespuestaPago = default(int), int secuencialEnvioPago = default(int), string operadoPor = default(string), string url = default(string), string factura = default(string), string informacionGenerica = default(string), string setLog = default(string), string idCliente = default(string), string nombreCliente = default(string))
        {
            this.FechaTransaccion = fechaTransaccion;
            this.Documento = documento;
            this.CodigoResultado = codigoResultado;
            this.FechaTransaccionFinancial = fechaTransaccionFinancial;
            this.HoraTransaccion = horaTransaccion;
            this.Mensaje = mensaje;
            this.ValorPagado = valorPagado;
            this.SecuencialRespuestaPago = secuencialRespuestaPago;
            this.SecuencialEnvioPago = secuencialEnvioPago;
            this.OperadoPor = operadoPor;
            this.Url = url;
            this.Factura = factura;
            this.InformacionGenerica = informacionGenerica;
            this.SetLog = setLog;
            this.IdCliente = idCliente;
            this.NombreCliente = nombreCliente;
        }

        /// <summary>
        /// Gets or Sets FechaTransaccion
        /// </summary>
        [DataMember(Name = "fechaTransaccion", EmitDefaultValue = true)]
        public string FechaTransaccion { get; set; }

        /// <summary>
        /// Gets or Sets Documento
        /// </summary>
        [DataMember(Name = "documento", EmitDefaultValue = true)]
        public string Documento { get; set; }

        /// <summary>
        /// Gets or Sets CodigoResultado
        /// </summary>
        [DataMember(Name = "codigoResultado", EmitDefaultValue = true)]
        public string CodigoResultado { get; set; }

        /// <summary>
        /// Gets or Sets FechaTransaccionFinancial
        /// </summary>
        [DataMember(Name = "fechaTransaccionFinancial", EmitDefaultValue = true)]
        public string FechaTransaccionFinancial { get; set; }

        /// <summary>
        /// Gets or Sets HoraTransaccion
        /// </summary>
        [DataMember(Name = "horaTransaccion", EmitDefaultValue = true)]
        public string HoraTransaccion { get; set; }

        /// <summary>
        /// Gets or Sets Mensaje
        /// </summary>
        [DataMember(Name = "mensaje", EmitDefaultValue = true)]
        public string Mensaje { get; set; }

        /// <summary>
        /// Gets or Sets ValorPagado
        /// </summary>
        [DataMember(Name = "valorPagado", EmitDefaultValue = false)]
        public double ValorPagado { get; set; }

        /// <summary>
        /// Gets or Sets SecuencialRespuestaPago
        /// </summary>
        [DataMember(Name = "secuencialRespuestaPago", EmitDefaultValue = false)]
        public int SecuencialRespuestaPago { get; set; }

        /// <summary>
        /// Gets or Sets SecuencialEnvioPago
        /// </summary>
        [DataMember(Name = "secuencialEnvioPago", EmitDefaultValue = false)]
        public int SecuencialEnvioPago { get; set; }

        /// <summary>
        /// Gets or Sets OperadoPor
        /// </summary>
        [DataMember(Name = "operadoPor", EmitDefaultValue = true)]
        public string OperadoPor { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets Factura
        /// </summary>
        [DataMember(Name = "factura", EmitDefaultValue = true)]
        public string Factura { get; set; }

        /// <summary>
        /// Gets or Sets InformacionGenerica
        /// </summary>
        [DataMember(Name = "informacionGenerica", EmitDefaultValue = true)]
        public string InformacionGenerica { get; set; }

        /// <summary>
        /// Gets or Sets SetLog
        /// </summary>
        [DataMember(Name = "setLog", EmitDefaultValue = true)]
        public string SetLog { get; set; }

        /// <summary>
        /// Gets or Sets IdCliente
        /// </summary>
        [DataMember(Name = "idCliente", EmitDefaultValue = true)]
        public string IdCliente { get; set; }

        /// <summary>
        /// Gets or Sets NombreCliente
        /// </summary>
        [DataMember(Name = "nombreCliente", EmitDefaultValue = true)]
        public string NombreCliente { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PagoFacilitoMS {\n");
            sb.Append("  FechaTransaccion: ").Append(FechaTransaccion).Append("\n");
            sb.Append("  Documento: ").Append(Documento).Append("\n");
            sb.Append("  CodigoResultado: ").Append(CodigoResultado).Append("\n");
            sb.Append("  FechaTransaccionFinancial: ").Append(FechaTransaccionFinancial).Append("\n");
            sb.Append("  HoraTransaccion: ").Append(HoraTransaccion).Append("\n");
            sb.Append("  Mensaje: ").Append(Mensaje).Append("\n");
            sb.Append("  ValorPagado: ").Append(ValorPagado).Append("\n");
            sb.Append("  SecuencialRespuestaPago: ").Append(SecuencialRespuestaPago).Append("\n");
            sb.Append("  SecuencialEnvioPago: ").Append(SecuencialEnvioPago).Append("\n");
            sb.Append("  OperadoPor: ").Append(OperadoPor).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Factura: ").Append(Factura).Append("\n");
            sb.Append("  InformacionGenerica: ").Append(InformacionGenerica).Append("\n");
            sb.Append("  SetLog: ").Append(SetLog).Append("\n");
            sb.Append("  IdCliente: ").Append(IdCliente).Append("\n");
            sb.Append("  NombreCliente: ").Append(NombreCliente).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
