/*
 * Corresponsales.Command.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Corresponsales.Command.Client.OpenAPIDateConverter;

namespace Corresponsales.Command.Model
{
    /// <summary>
    /// PagoCuentaResponse
    /// </summary>
    [DataContract(Name = "PagoCuentaResponse")]
    public partial class PagoCuentaResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PagoCuentaResponse" /> class.
        /// </summary>
        /// <param name="documento">documento</param>
        /// <param name="valor">valor</param>
        /// <param name="detalle">detalle</param>
        public PagoCuentaResponse(string documento = default(string), decimal? valor = default(decimal?), string detalle = default(string))
        {
            this.Documento = documento;
            this.Valor = valor;
            this.Detalle = detalle;
        }

        /// <summary>
        /// Gets or Sets Documento
        /// </summary>
        [DataMember(Name = "documento", EmitDefaultValue = true)]
        public string Documento { get; set; }

        /// <summary>
        /// Gets or Sets Valor
        /// </summary>
        [DataMember(Name = "valor", EmitDefaultValue = true)]
        public decimal? Valor { get; set; }

        /// <summary>
        /// Gets or Sets Detalle
        /// </summary>
        [DataMember(Name = "detalle", EmitDefaultValue = true)]
        public string Detalle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PagoCuentaResponse {\n");
            sb.Append("  Documento: ").Append(Documento).Append("\n");
            sb.Append("  Valor: ").Append(Valor).Append("\n");
            sb.Append("  Detalle: ").Append(Detalle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
