/*
 * Corresponsales.Command.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Corresponsales.Command.Client.OpenAPIDateConverter;

namespace Corresponsales.Command.Model
{
    /// <summary>
    /// ProcesaReimpresionPagoServicioResponse
    /// </summary>
    [DataContract(Name = "ProcesaReimpresionPagoServicioResponse")]
    public partial class ProcesaReimpresionPagoServicioResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProcesaReimpresionPagoServicioResponse" /> class.
        /// </summary>
        /// <param name="codigoEstado">codigoEstado.</param>
        /// <param name="mensaje">mensaje.</param>
        /// <param name="datos">datos.</param>
        public ProcesaReimpresionPagoServicioResponse(int codigoEstado = default(int), string mensaje = default(string), DatosReimpresionPago datos = default(DatosReimpresionPago))
        {
            this.CodigoEstado = codigoEstado;
            this.Mensaje = mensaje;
            this.Datos = datos;
        }

        /// <summary>
        /// Gets or Sets CodigoEstado
        /// </summary>
        [DataMember(Name = "codigoEstado", EmitDefaultValue = false)]
        public int CodigoEstado { get; set; }

        /// <summary>
        /// Gets or Sets Mensaje
        /// </summary>
        [DataMember(Name = "mensaje", EmitDefaultValue = true)]
        public string Mensaje { get; set; }

        /// <summary>
        /// Gets or Sets Datos
        /// </summary>
        [DataMember(Name = "datos", EmitDefaultValue = false)]
        public DatosReimpresionPago Datos { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProcesaReimpresionPagoServicioResponse {\n");
            sb.Append("  CodigoEstado: ").Append(CodigoEstado).Append("\n");
            sb.Append("  Mensaje: ").Append(Mensaje).Append("\n");
            sb.Append("  Datos: ").Append(Datos).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}