/*
 * Corresponsales.Command.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Corresponsales.Command.Client.OpenAPIDateConverter;

namespace Corresponsales.Command.Model
{
    /// <summary>
    /// ReciboPagos
    /// </summary>
    [DataContract(Name = "ReciboPagos")]
    public partial class ReciboPagos : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReciboPagos" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="numero">numero.</param>
        /// <param name="importes">importes.</param>
        /// <param name="fechaVencimiento">fechaVencimiento.</param>
        public ReciboPagos(string id = default(string), string numero = default(string), List<ImporteReciboPagos> importes = default(List<ImporteReciboPagos>), DateTime fechaVencimiento = default(DateTime))
        {
            this.Id = id;
            this.Numero = numero;
            this.Importes = importes;
            this.FechaVencimiento = fechaVencimiento;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Numero
        /// </summary>
        [DataMember(Name = "numero", EmitDefaultValue = true)]
        public string Numero { get; set; }

        /// <summary>
        /// Gets or Sets Importes
        /// </summary>
        [DataMember(Name = "importes", EmitDefaultValue = true)]
        public List<ImporteReciboPagos> Importes { get; set; }

        /// <summary>
        /// Gets or Sets FechaVencimiento
        /// </summary>
        [DataMember(Name = "fechaVencimiento", EmitDefaultValue = false)]
        public DateTime FechaVencimiento { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReciboPagos {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Numero: ").Append(Numero).Append("\n");
            sb.Append("  Importes: ").Append(Importes).Append("\n");
            sb.Append("  FechaVencimiento: ").Append(FechaVencimiento).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}