/*
 * Corresponsales.Command.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Corresponsales.Command.Client.OpenAPIDateConverter;

namespace Corresponsales.Command.Model
{
    /// <summary>
    /// RubroRequest
    /// </summary>
    [DataContract(Name = "RubroRequest")]
    public partial class RubroRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RubroRequest" /> class.
        /// </summary>
        /// <param name="prioridad">prioridad.</param>
        /// <param name="periodo">periodo.</param>
        /// <param name="medidor">medidor.</param>
        /// <param name="tipo">tipo.</param>
        /// <param name="valorPagado">valorPagado.</param>
        /// <param name="idPago">idPago.</param>
        /// <param name="pagoParcial">pagoParcial.</param>
        public RubroRequest(int prioridad = default(int), string periodo = default(string), string medidor = default(string), string tipo = default(string), double valorPagado = default(double), string idPago = default(string), string pagoParcial = default(string))
        {
            this.Prioridad = prioridad;
            this.Periodo = periodo;
            this.Medidor = medidor;
            this.Tipo = tipo;
            this.ValorPagado = valorPagado;
            this.IdPago = idPago;
            this.PagoParcial = pagoParcial;
        }

        /// <summary>
        /// Gets or Sets Prioridad
        /// </summary>
        [DataMember(Name = "prioridad", EmitDefaultValue = false)]
        public int Prioridad { get; set; }

        /// <summary>
        /// Gets or Sets Periodo
        /// </summary>
        [DataMember(Name = "periodo", EmitDefaultValue = true)]
        public string Periodo { get; set; }

        /// <summary>
        /// Gets or Sets Medidor
        /// </summary>
        [DataMember(Name = "medidor", EmitDefaultValue = true)]
        public string Medidor { get; set; }

        /// <summary>
        /// Gets or Sets Tipo
        /// </summary>
        [DataMember(Name = "tipo", EmitDefaultValue = true)]
        public string Tipo { get; set; }

        /// <summary>
        /// Gets or Sets ValorPagado
        /// </summary>
        [DataMember(Name = "valorPagado", EmitDefaultValue = false)]
        public double ValorPagado { get; set; }

        /// <summary>
        /// Gets or Sets IdPago
        /// </summary>
        [DataMember(Name = "idPago", EmitDefaultValue = true)]
        public string IdPago { get; set; }

        /// <summary>
        /// Gets or Sets PagoParcial
        /// </summary>
        [DataMember(Name = "pagoParcial", EmitDefaultValue = true)]
        public string PagoParcial { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RubroRequest {\n");
            sb.Append("  Prioridad: ").Append(Prioridad).Append("\n");
            sb.Append("  Periodo: ").Append(Periodo).Append("\n");
            sb.Append("  Medidor: ").Append(Medidor).Append("\n");
            sb.Append("  Tipo: ").Append(Tipo).Append("\n");
            sb.Append("  ValorPagado: ").Append(ValorPagado).Append("\n");
            sb.Append("  IdPago: ").Append(IdPago).Append("\n");
            sb.Append("  PagoParcial: ").Append(PagoParcial).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
